lint:
  - "**/*.sh"
  - "**/*.bash"
  - "**/*.bats"
validate:
  - "**/metadata.yaml"
  - "**/*.schema.json"
unit_test:
  - "lib/*.sh"
  - "lib/*.bash"
  - "lib/*.json"
  - "test/unit/**"
scenario_test:
  - "features/bootstrap.sh"
  - "lib/**"
  - "test/lib/**"
devcontainer:
  - ".devcontainer/.dev/**"
