"""Unit tests for proman.test.codegen — .sh generation from checks.yaml."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

import pytest
import yaml
from proman.test.codegen import _render_group, generate_tests

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_group(yaml_text: str) -> tuple[str, dict]:
    data = yaml.safe_load(yaml_text)
    test_id, group = next(iter(data.items()))
    return test_id, group


# ---------------------------------------------------------------------------
# Header / boilerplate
# ---------------------------------------------------------------------------


class TestHeader:
    """Tests for the header and boilerplate section of generated .sh files."""

    def test_shebang_and_set_e(self) -> None:
        """Shebang and set -e appear in generated output."""
        _, g = _load_group("my_test:\n  checks:\n    - title: t\n      cmd: true\n")
        out = _render_group("my_test", g)
        assert out.startswith("#!/usr/bin/env bash\n")
        assert "set -e\n" in out

    def test_source_line(self) -> None:
        """Source line for the test lib is present."""
        _, g = _load_group("t:\n  checks:\n    - title: t\n      cmd: true\n")
        out = _render_group("t", g)
        assert ". dev-container-features-test-lib\n" in out

    def test_autogenerated_marker(self) -> None:
        """AUTO-GENERATED marker is present."""
        _, g = _load_group("t:\n  checks:\n    - title: t\n      cmd: true\n")
        out = _render_group("t", g)
        assert "# AUTO-GENERATED from checks.yaml" in out

    def test_no_description(self) -> None:
        """No description leaves no comment before the AUTO-GENERATED marker."""
        _, g = _load_group("t:\n  checks:\n    - title: t\n      cmd: true\n")
        out = _render_group("t", g)
        # No extra comment lines before the AUTO-GENERATED marker.
        lines = out.splitlines()
        assert lines[0] == "#!/usr/bin/env bash"
        assert lines[1] == "# AUTO-GENERATED from checks.yaml \u2014 DO NOT EDIT"

    def test_description_appears_before_marker(self) -> None:
        """Description comment precedes the AUTO-GENERATED marker."""
        _, g = _load_group(
            "t:\n  description: 'Verify yq is installed.'\n"
            "  checks:\n    - title: t\n      cmd: true\n"
        )
        out = _render_group("t", g)
        lines = out.splitlines()
        assert lines[1] == "# Verify yq is installed."
        assert lines[2] == "# AUTO-GENERATED from checks.yaml \u2014 DO NOT EDIT"

    def test_multiline_description(self) -> None:
        """Multi-line description is emitted as comment lines."""
        _, g = _load_group(
            "t:\n  description: |\n    Line one.\n    Line two.\n"
            "  checks:\n    - title: t\n      cmd: true\n"
        )
        out = _render_group("t", g)
        assert "# Line one.\n# Line two.\n" in out

    def test_ends_with_report_results(self) -> None:
        """Output ends with reportResults."""
        _, g = _load_group("t:\n  checks:\n    - title: t\n      cmd: true\n")
        out = _render_group("t", g)
        assert out.endswith("\nreportResults\n")


# ---------------------------------------------------------------------------
# Simple check items
# ---------------------------------------------------------------------------


class TestCheckItem:
    """Tests for individual check/fail_check item rendering."""

    def test_simple_check(self) -> None:
        """Simple check call is emitted correctly."""
        _, g = _load_group(
            "t:\n  checks:\n    - title: 'yq available'\n      cmd: 'command -v yq'\n"
        )
        out = _render_group("t", g)
        assert 'check "yq available" command -v yq\n' in out

    def test_kind_fail(self) -> None:
        """fail_check is emitted for kind=fail."""
        _, g = _load_group(
            "t:\n  checks:\n"
            "    - title: 'cmd fails'\n      cmd: 'false'\n      kind: fail\n"
        )
        out = _render_group("t", g)
        assert 'fail_check "cmd fails" false\n' in out

    def test_kind_check_explicit(self) -> None:
        """Explicit kind=check still emits check."""
        _, g = _load_group(
            "t:\n  checks:\n    - title: 'ok'\n      cmd: 'true'\n      kind: check\n"
        )
        out = _render_group("t", g)
        assert 'check "ok" true\n' in out

    def test_title_with_double_quotes_escaped(self) -> None:
        """Double quotes in a title are escaped."""
        _, g = _load_group(
            "T:\n  checks:\n    - title: 'a \"quoted\" title'\n      cmd: true\n"
        )
        out = _render_group("T", g)
        assert 'check "a \\"quoted\\" title" true\n' in out

    def test_multiline_cmd_backslash_continuation(self) -> None:
        """Multiline cmd uses backslash continuation."""
        yaml_text = (
            "t:\n"
            "  checks:\n"
            "    - title: 'multi'\n"
            "      cmd: |\n"
            "        bash -c \\\n"
            "          'test -f /a'\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert 'check "multi" \\\n' in out
        assert "  bash -c \\\n" in out


# ---------------------------------------------------------------------------
# Tests for kind=multiple
# ---------------------------------------------------------------------------


class TestCheckMultiple:
    """Tests for kind=multiple check rendering."""

    def test_check_multiple_basic(self) -> None:
        """Basic checkMultiple call with min=1."""
        yaml_text = (
            "t:\n"
            "  checks:\n"
            "    - title: 'at least one'\n"
            "      kind: multiple\n"
            "      min: 1\n"
            "      cmd:\n"
            "        - test -f /a\n"
            "        - test -f /b\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert 'checkMultiple "at least one" 1 \\' in out
        assert '  "test -f /a" \\' in out
        assert '  "test -f /b"' in out
        # Last item must NOT have trailing backslash.
        assert '  "test -f /b"\n' in out

    def test_check_multiple_min_2(self) -> None:
        """CheckMultiple with min=2 emits the correct minimum."""
        yaml_text = (
            "t:\n"
            "  checks:\n"
            "    - title: 'two of three'\n"
            "      kind: multiple\n"
            "      min: 2\n"
            "      cmd:\n"
            "        - test -f /x\n"
            "        - test -f /y\n"
            "        - test -f /z\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert 'checkMultiple "two of three" 2 \\' in out

    def test_check_multiple_cmd_double_quotes_escaped(self) -> None:
        r"""Double quotes inside cmd strings are escaped so each cmd is one argument.

        Without escaping, a cmd like bash -c 'grep -q "^ii"' generates the broken
        shell argument "bash -c 'grep -q "^ii"'", which the shell splits at the inner
        double-quote.  With escaping it becomes "bash -c 'grep -q \"^ii\"'" — a
        single, syntactically valid double-quoted string passed to checkMultiple.
        """
        yaml_text = (
            "t:\n"
            "  checks:\n"
            "    - title: 'pkg managed'\n"
            "      kind: multiple\n"
            "      min: 1\n"
            "      cmd:\n"
            "        - bash -c 'dpkg -l foo 2>/dev/null | grep -q \"^ii\"'\n"
            "        - bash -c 'rpm -q foo >/dev/null 2>&1'\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        # Inner double-quotes must be escaped so the outer wrapping is a valid argument.
        assert '  "bash -c \'dpkg -l foo 2>/dev/null | grep -q \\"^ii\\"\'"' in out
        # Command without inner quotes is unchanged.
        assert "  \"bash -c 'rpm -q foo >/dev/null 2>&1'\"" in out


# ---------------------------------------------------------------------------
# debug / on_fail fields
# ---------------------------------------------------------------------------


class TestDebugOnFail:
    """Tests for debug and on_fail field rendering."""

    def test_debug_emitted_before_check(self) -> None:
        """Debug output is emitted before its associated check call."""
        yaml_text = (
            "t:\n"
            "  checks:\n"
            "    - title: 'check path'\n"
            "      cmd: 'test -f /x'\n"
            "      debug: 'echo \"=== /x ===\"'\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        debug_pos = out.index('echo "=== /x ==="')
        check_pos = out.index('check "check path"')
        assert debug_pos < check_pos

    def test_on_fail_snapshot_and_guard(self) -> None:
        """on_fail emits a snapshot variable and a conditional guard block."""
        yaml_text = (
            "t:\n"
            "  checks:\n"
            "    - title: 'check x'\n"
            "      cmd: 'test -f /x'\n"
            "      on_fail: 'ls -la /x || true'\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert '_df0="$_TEST_FAIL"' in out
        assert '[ "$_TEST_FAIL" -eq "$_df0" ] || {' in out
        assert "ls -la /x || true" in out

    def test_on_fail_index_increments(self) -> None:
        """Two checks with on_fail use distinct index variables."""
        yaml_text = (
            "t:\n"
            "  checks:\n"
            "    - title: 'a'\n      cmd: 'true'\n      on_fail: 'echo a'\n"
            "    - title: 'b'\n      cmd: 'true'\n"
            "    - title: 'c'\n      cmd: 'true'\n      on_fail: 'echo c'\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert '_df0="$_TEST_FAIL"' in out
        assert '_df2="$_TEST_FAIL"' in out
        # Index 1 has no on_fail.
        assert '_df1="$_TEST_FAIL"' not in out


# ---------------------------------------------------------------------------
# post / on_failure / pre group fields
# ---------------------------------------------------------------------------


class TestGroupFields:
    """Tests for group-level fields: post, on_failure, and pre."""

    def test_post_generates_cleanup(self) -> None:
        """Post field generates a _cleanup() function and trap."""
        yaml_text = (
            "t:\n  post: 'rm -f /tmp/x'\n  checks:\n    - title: t\n      cmd: true\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert "_cleanup() {" in out
        assert "  rm -f /tmp/x" in out
        assert "trap _cleanup EXIT" in out

    def test_post_trap_before_test_failure_diag(self) -> None:
        """Trap _cleanup EXIT appears before _test_failure_diagnostics."""
        yaml_text = (
            "t:\n"
            "  post: 'cleanup body'\n"
            "  on_failure: 'diag body'\n"
            "  checks:\n    - title: t\n      cmd: true\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        trap_pos = out.index("trap _cleanup EXIT")
        diag_pos = out.index("_test_failure_diagnostics()")
        assert trap_pos < diag_pos

    def test_on_failure_generates_diag_function(self) -> None:
        """on_failure field generates a _test_failure_diagnostics() function."""
        yaml_text = (
            "t:\n"
            "  on_failure: 'cat /var/log/foo'\n"
            "  checks:\n    - title: t\n      cmd: true\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert "_test_failure_diagnostics() {" in out
        assert "  cat /var/log/foo" in out

    def test_pre_content_verbatim(self) -> None:
        """Pre content is emitted verbatim before check calls."""
        yaml_text = (
            "t:\n"
            "  pre: '_VAR=\"$(command -v yq)\"'\n"
            "  checks:\n    - title: t\n      cmd: true\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert '_VAR="$(command -v yq)"' in out

    def test_pre_appears_before_checks(self) -> None:
        """Pre content appears before any check calls in the output."""
        yaml_text = "t:\n  pre: '_X=1'\n  checks:\n    - title: t\n      cmd: true\n"
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        pre_pos = out.index("_X=1")
        check_pos = out.index('check "t"')
        assert pre_pos < check_pos

    def test_no_post_no_cleanup(self) -> None:
        """Absence of post means no _cleanup function is generated."""
        _, g = _load_group("t:\n  checks:\n    - title: t\n      cmd: true\n")
        out = _render_group("t", g)
        assert "_cleanup" not in out

    def test_no_on_failure_no_diag(self) -> None:
        """Absence of on_failure means no diagnostics function is generated."""
        _, g = _load_group("t:\n  checks:\n    - title: t\n      cmd: true\n")
        out = _render_group("t", g)
        assert "_test_failure_diagnostics" not in out


# ---------------------------------------------------------------------------
# generate_tests() — file I/O
# ---------------------------------------------------------------------------


class TestGenerateTests:
    """Tests for the generate_tests() file I/O entry point."""

    def test_writes_sh_files(self, tmp_path: Path) -> None:
        """.sh files are written to the output directory."""
        checks_yaml = tmp_path / "checks.yaml"
        checks_yaml.write_text(
            "default_install:\n"
            "  description: 'Verify yq.'\n"
            "  checks:\n"
            "    - title: 'yq available'\n"
            "      cmd: 'command -v yq'\n",
            encoding="utf-8",
        )
        out_dir = tmp_path / "tests"
        generate_tests("install-yq", checks_yaml, out_dir)
        assert (out_dir / "default_install.sh").exists()

    def test_generated_content_is_valid(self, tmp_path: Path) -> None:
        """Generated .sh file has valid structure and contains the check call."""
        checks_yaml = tmp_path / "checks.yaml"
        checks_yaml.write_text(
            "my_test:\n  checks:\n    - title: 'pass'\n      cmd: 'true'\n",
            encoding="utf-8",
        )
        out_dir = tmp_path / "tests"
        generate_tests("feat", checks_yaml, out_dir)
        content = (out_dir / "my_test.sh").read_text(encoding="utf-8")
        assert content.startswith("#!/usr/bin/env bash\n")
        assert 'check "pass" true\n' in content
        assert content.endswith("\nreportResults\n")

    def test_file_is_executable(self, tmp_path: Path) -> None:
        """Generated .sh files have the executable bit set."""
        checks_yaml = tmp_path / "checks.yaml"
        checks_yaml.write_text(
            "t:\n  checks:\n    - title: t\n      cmd: true\n",
            encoding="utf-8",
        )
        out_dir = tmp_path / "tests"
        generate_tests("feat", checks_yaml, out_dir)
        sh = out_dir / "t.sh"
        assert sh.stat().st_mode & 0o111, "generated .sh should be executable"

    def test_multiple_test_ids_each_get_own_file(self, tmp_path: Path) -> None:
        """Each test group in checks.yaml gets its own .sh file."""
        checks_yaml = tmp_path / "checks.yaml"
        checks_yaml.write_text(
            "default_install:\n"
            "  checks:\n    - title: a\n      cmd: true\n"
            "shell_completion_zsh:\n"
            "  checks:\n    - title: b\n      cmd: true\n",
            encoding="utf-8",
        )
        out_dir = tmp_path / "tests"
        generate_tests("feat", checks_yaml, out_dir)
        assert (out_dir / "default_install.sh").exists()
        assert (out_dir / "shell_completion_zsh.sh").exists()


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestEdgeCases:
    """Edge-case and parametrize tests for check rendering."""

    def test_empty_debug_field_omitted(self) -> None:
        """Empty debug field does not emit extra output before the check."""
        yaml_text = "t:\n  checks:\n    - title: t\n      cmd: true\n      debug: ''\n"
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        # Empty debug must not emit a bare newline before the check
        check_idx = out.index('check "t"')
        # The character immediately before check should be a newline (section separator)
        assert out[check_idx - 1] == "\n"

    def test_empty_on_fail_field_omitted(self) -> None:
        """Empty on_fail field does not emit a snapshot variable or guard."""
        yaml_text = (
            "t:\n  checks:\n    - title: t\n      cmd: true\n      on_fail: ''\n"
        )
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert "_df0" not in out

    @pytest.mark.parametrize(
        ("title", "expected"),
        [
            ("simple", '"simple"'),
            ('with "quotes"', '"with \\"quotes\\""'),
        ],
    )
    def test_title_quoting(self, title: str, expected: str) -> None:
        """Titles are wrapped in double quotes with interior quotes escaped."""
        yaml_text = f"t:\n  checks:\n    - title: '{title}'\n      cmd: true\n"
        _, g = _load_group(yaml_text)
        out = _render_group("t", g)
        assert expected in out
