#!/usr/bin/env python3
"""argparse.py — Generates the full header of each feature's install.bash.

The generated content covers everything from the shebang (#!/usr/bin/env bash)
through the argument-parsing block and default-variable initialisation, and is
terminated by a single end marker:

    # END OF AUTOGENERATED BLOCK

Everything after that marker in the file is hand-written implementation code
and is never touched by this script.

Options with ``type: array`` in metadata.yaml are treated as bash arrays:
  * CLI branch:      --flag <value>  (repeatable; each invocation appends)
  * env-var branch:  newline-delimited string split into an array
  * Defaults:        empty array  ()

The ``type: array`` is serialised as ``type: string`` in devcontainer-feature.json
(handled by metadata.py).

Usage:
  python3 scripts/_sync-src/argparse.py           # update all install.bash files
  python3 scripts/_sync-src/argparse.py --check   # exit non-zero if any block is stale
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from git_utils import git_repo_root

MARKER_END = "# END OF AUTOGENERATED BLOCK"

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = git_repo_root()
FEATURES_DIR = REPO_ROOT / "features"
SRC_DIR = REPO_ROOT / "src"
TEMPLATES_DIR = FEATURES_DIR / "_templates"
_DERIVED_OPTIONS_PATH = FEATURES_DIR / "derived-options.yaml"

# ---------------------------------------------------------------------------
# Derived (synthetic) options — loaded from shared YAML
# ---------------------------------------------------------------------------

with _DERIVED_OPTIONS_PATH.open(encoding="utf-8") as _fh:
    _DERIVED_OPTIONS: dict = yaml.safe_load(_fh)

# All keys that the generators manage (strip from raw metadata before re-injecting).
_DERIVED_OPTION_KEYS: frozenset[str] = frozenset(_DERIVED_OPTIONS)


def _synthetic(key: str) -> dict:
    """Return the option schema for a derived key, stripping the 'inject' meta-field."""
    return {k: v for k, v in _DERIVED_OPTIONS[key].items() if k != "inject"}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def strip_markdown(text: str) -> str:
    """Strip markdown formatting for plain-text display in usage strings."""
    if not text:
        return text
    # [link text](url) → link text
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    # **bold** → bold
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    # *italic* → italic
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    return text.strip()


def first_sentence(text: str) -> str:
    """Return the first non-empty line of a description."""
    for line in text.splitlines():
        line = line.strip()
        if line:
            return line
    return text.strip()


def opt_to_var(key: str) -> str:
    """Convert an option key (snake_case or kebab-case) to UPPER_SNAKE_CASE var name."""
    return key.upper().replace("-", "_")


def opt_to_flag(key: str) -> str:
    """Convert an option key to its --flag form."""
    return f"--{key}"


def shell_val(default, typ: str) -> str:
    """Format a YAML default value as a shell assignment RHS (non-array types only)."""
    if typ == "boolean":
        return "true" if default else "false"
    if default == "" or default is None:
        return '""'
    return f'"{default}"'


def usage_type_hint(opt: dict) -> str:
    """Return a concise type hint for the --help usage line."""
    typ = opt.get("type", "string")
    enum_raw = opt.get("enum", [])
    enum_values = [item["value"] if isinstance(item, dict) else str(item) for item in enum_raw]
    if typ == "boolean":
        return "{true,false}"
    if typ == "array":
        if enum_values:
            return "{" + "|".join(enum_values) + "}  (repeatable)"
        return "<value>  (repeatable)"
    if enum_values:
        return "{" + "|".join(enum_values) + "}"
    return "<value>"


# ---------------------------------------------------------------------------
# Block generator — section emitters
# ---------------------------------------------------------------------------


def _load_header(feature_name: str) -> str:
    """Load features/install.bash.header and substitute @@FEATURE_NAME@@."""
    tpl = (FEATURES_DIR / "install.bash.header").read_text(encoding="utf-8")
    return tpl.replace("@@FEATURE_NAME@@", feature_name).rstrip("\n")


def _render(name: str, **subs: str) -> str:
    """Load a shell snippet template from features/_templates/ and substitute @@KEY@@ placeholders."""
    tpl = (TEMPLATES_DIR / name).read_text(encoding="utf-8").rstrip("\n")
    for key, val in subs.items():
        tpl = tpl.replace(f"@@{key}@@", val)
    return tpl


def _section_usage(options: dict) -> str:
    """Emit the __usage__() shell function."""
    entries: list[tuple[str, str, str, bool]] = []
    for key, opt in options.items():
        typ = opt["type"]
        flag_str = f"  {opt_to_flag(key)} {usage_type_hint(opt)}"
        has_default = "default" in opt
        default = opt.get("default", "")
        is_required = not has_default
        if typ == "boolean":
            disp_default = "true" if default else "false"
        elif typ == "array":
            disp_default = ""
        else:
            disp_default = str(default) if has_default and default is not None else ""
        desc = first_sentence(strip_markdown(opt.get("description", "")))
        entries.append((flag_str, desc, disp_default, is_required))

    help_flag = "  -h, --help"
    col_width = max((len(f) for f, *_ in entries), default=len(help_flag))
    col_width = max(col_width, len(help_flag))

    lines = ["__usage__() {", "  cat << 'EOF'", "Usage: install.bash [OPTIONS]", "", "Options:"]
    for (flag_str, desc, disp_default, is_required), _ in zip(entries, options.items()):
        padding = " " * (col_width - len(flag_str) + 2)
        if is_required:
            desc_field = f"{desc} (required)"
        elif disp_default:
            desc_field = f'{desc} (default: "{disp_default}")'
        else:
            desc_field = desc
        lines.append(f"{flag_str}{padding}{desc_field}")
    help_padding = " " * (col_width - len(help_flag) + 2)
    lines.append(f"{help_flag}{help_padding}Show this help")
    lines.extend(["EOF", "  return", "}"])
    return "\n".join(lines)


def _section_arg_parse(options: dict) -> str:
    """Emit the if/else/fi CLI-vs-env-var argument parsing block."""
    cli_inits: list[str] = []
    case_arms: list[str] = []
    env_reads: list[str] = []

    for key, opt in options.items():
        vname = opt_to_var(key)
        typ = opt.get("type", "string")
        flag = opt_to_flag(key)
        # Arrays are intentionally NOT pre-initialised: bash +=() on an unset variable
        # is safe, and pre-setting to () would fool the declare-based default check.
        if typ != "array":
            if "default" not in opt:
                cli_inits.append(f'  {vname}=""')
            else:
                cli_inits.append(f"  {vname}={shell_val(opt['default'], typ)}")
        if typ == "array":
            case_arms.append(_render("case_arm_array.sh.tmpl", FLAG=flag, VAR=vname, KEY=key))
            env_reads.append(_render("env_read_array.sh.tmpl", VAR=vname, KEY=key))
        else:
            case_arms.append(_render("case_arm_scalar.sh.tmpl", FLAG=flag, VAR=vname, KEY=key))
            env_reads.append(_render("env_read_scalar.sh.tmpl", VAR=vname, KEY=key))

    lines = [
        'if [ "$#" -gt 0 ]; then',
        '  echo "ℹ️ Script called with arguments: $*" >&2',
    ]
    lines.extend(cli_inits)
    lines.extend(['  while [ "$#" -gt 0 ]; do', "    case $1 in"])
    lines.extend(case_arms)
    lines.extend([
        "      -h | --help)",
        "        __usage__",
        "        exit 0",
        "        ;;",
        "      --*)",
        "        echo \"⛔ Unknown option: '${1}'\" >&2",
        "        exit 1",
        "        ;;",
        "      *)",
        "        echo \"⛔ Unexpected argument: '${1}'\" >&2",
        "        exit 1",
        "        ;;",
        "    esac",
        "  done",
        "else",
        '  echo "ℹ️ Script called with no arguments. Read environment variables." >&2',
    ])
    lines.extend(env_reads)
    lines.append("fi")
    return "\n".join(lines)


def _section_debug_flag() -> str:
    return '[[ "${DEBUG:-}" == true ]] && set -x'


def _section_defaults(options: dict) -> str:
    """Emit the '# Apply defaults.' block."""
    blocks = ["# Apply defaults."]
    for key, opt in options.items():
        vname = opt_to_var(key)
        typ = opt.get("type", "string")
        if "default" not in opt:
            continue
        if typ == "array":
            raw_default = opt["default"]
            if raw_default == "" or raw_default is None:
                blocks.append(_render("default_array_empty.sh.tmpl", VAR=vname, KEY=key))
            else:
                # Embed the default as an ANSI-C quoted string so newlines are preserved.
                escaped = (
                    str(raw_default)
                    .replace("\\", "\\\\")
                    .replace("'", "\\'")
                    .replace("\n", "\\n")
                    .replace("\r", "\\r")
                )
                disp = ", ".join(str(raw_default).splitlines())
                blocks.append(_render("default_array_value.sh.tmpl", VAR=vname, ESCAPED=escaped, KEY=key, DISP=disp))
        else:
            rhs = shell_val(opt["default"], typ)
            if typ == "boolean":
                disp = "true" if opt["default"] else "false"
            elif opt["default"] == "" or opt["default"] is None:
                disp = ""
            else:
                disp = str(opt["default"])
            blocks.append(_render("default_scalar.sh.tmpl", VAR=vname, RHS=rhs, KEY=key, DISP=disp))
    return "\n".join(blocks)


def _section_validation(options: dict) -> str:
    """Emit required-argument checks and enum validation. Returns '' if neither applies."""
    required_opts = [(k, v) for k, v in options.items() if "default" not in v]
    enum_opts = [(k, v) for k, v in options.items() if v.get("enum")]
    if not required_opts and not enum_opts:
        return ""

    parts: list[str] = []
    if required_opts:
        checks: list[str] = []
        for key, opt in required_opts:
            vname = opt_to_var(key)
            tpl = "validation_required_array.sh.tmpl" if opt.get("type", "string") == "array" else "validation_required_scalar.sh.tmpl"
            checks.append(_render(tpl, VAR=vname, KEY=key))
        parts.append("# Check required arguments.\n" + "\n".join(checks))

    if enum_opts:
        validations: list[str] = []
        for key, opt in enum_opts:
            vname = opt_to_var(key)
            typ = opt.get("type", "string")
            values = [item["value"] if isinstance(item, dict) else str(item) for item in opt["enum"]]
            expected = ", ".join(repr(v) if v == "" else v for v in values)
            pattern = " | ".join("''" if v == "" else v for v in values)
            tpl = "validation_enum_array.sh.tmpl" if typ == "array" else "validation_enum_scalar.sh.tmpl"
            validations.append(_render(tpl, VAR=vname, KEY=key, PATTERN=pattern, EXPECTED=expected))
        parts.append("# Validate enum options.\n" + "\n".join(validations))

    return "\n\n".join(parts)


def _section_unexport(options: dict) -> str:
    """Emit the 'declare +x' unexport line for all scalar option variables."""
    scalar_vars = [
        opt_to_var(k) for k, v in options.items() if v.get("type", "string") != "array"
    ]
    if not scalar_vars:
        return ""
    return "\n".join([
        "# Unexport option variables — values remain accessible in this script but",
        "# are not inherited by child processes.",
        "declare +x " + " ".join(scalar_vars),
    ])


def _section_dep_helpers(run_deps: dict, build_deps: dict) -> str:
    """Emit _<group>_deps__install() / _<group>_deps__cleanup() helper functions."""
    if not run_deps and not build_deps:
        return ""
    blocks = ["# ── dep-group helpers (generated) ──────────────────────────────────────────────"]
    for group_name in run_deps:
        blocks.append(_render("dep_helper_run.sh.tmpl", SAFE=group_name.replace("-", "_"), GROUP=group_name))
    for group_name in build_deps:
        blocks.append(_render("dep_helper_build.sh.tmpl", SAFE=group_name.replace("-", "_"), GROUP=group_name))
    return "\n".join(blocks)


def _section_base_deps_call(run_deps: dict) -> str:
    """Emit the root-guarded _base_deps__install() call, or '' if no base group."""
    if "base" not in run_deps:
        return ""
    return _render("base_deps_call.sh.tmpl")


def generate_block(feature_name: str, options: dict, dependencies: dict | None = None) -> str:
    """Return the full generated content from shebang to END marker (inclusive).

    The returned string ends with ``# END OF AUTOGENERATED BLOCK\\n``.
    If ``_dependencies.run`` contains a ``base`` key, a ``_base_deps__install``
    call is emitted as the last statement before the end marker.
    If ``_dependencies.build`` is non-empty, dep-group helper functions are emitted.
    """
    run_deps: dict = (dependencies or {}).get("run") or {}
    build_deps: dict = (dependencies or {}).get("build") or {}

    # All derived keys are always stripped and re-injected unconditionally.
    core_options = {k: v for k, v in options.items() if k not in _DERIVED_OPTION_KEYS}
    options = {**core_options, **{k: _synthetic(k) for k in _DERIVED_OPTIONS}}

    parts = [
        _load_header(feature_name),
        _section_usage(options),
        _section_arg_parse(options),
        _section_debug_flag(),
        _section_defaults(options),
        _section_validation(options),
        _section_unexport(options),
        _section_dep_helpers(run_deps, build_deps),
        _section_base_deps_call(run_deps),
        MARKER_END,
    ]
    return "\n\n".join(p for p in parts if p) + "\n"


# ---------------------------------------------------------------------------
# shfmt post-processing
# ---------------------------------------------------------------------------


def _shfmt_format(text: str) -> str:
    """Format a bash script fragment through shfmt, respecting .editorconfig.

    Writes to a temp file in the repo root so shfmt finds the .editorconfig
    style settings.  Returns *text* unchanged if shfmt is not on PATH.
    """
    repo_root = REPO_ROOT
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".sh",
        dir=repo_root,
        delete=False,
        encoding="utf-8",
    ) as tmp:
        tmp.write(text)
        tmp_path = Path(tmp.name)
    try:
        result = subprocess.run(
            ["shfmt", "-w", str(tmp_path)],
            capture_output=True,
            cwd=repo_root,
        )
        if result.returncode == 0:
            return tmp_path.read_text(encoding="utf-8")
        return text
    except FileNotFoundError:
        return text
    finally:
        tmp_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# File update
# ---------------------------------------------------------------------------


def write_assembled(body_path: Path, target_path: Path, new_block: str) -> tuple[bool, str]:
    """Assemble header + body and write to *target_path*.

    *body_path*   — features/<f>/install.bash  (body only, no header/marker)
    *target_path* — src/<f>/install.bash       (assembled output)

    Returns (changed, error_message).  *error_message* is empty on success.
    """
    body = body_path.read_text(encoding="utf-8").lstrip("\n")
    new_text = new_block + ("\n" + body if body else "")

    target_path.parent.mkdir(parents=True, exist_ok=True)
    current = target_path.read_text(encoding="utf-8") if target_path.exists() else None

    if new_text == current:
        return False, ""
    target_path.write_text(new_text, encoding="utf-8")
    return True, ""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    check_mode = "--check" in sys.argv

    feature_dirs = sorted(FEATURES_DIR.glob("*/metadata.yaml"))
    if not feature_dirs:
        print(f"⛔ No metadata.yaml files found under {FEATURES_DIR}", file=sys.stderr)
        return 1

    any_stale = False
    any_error = False

    for meta_path in feature_dirs:
        feature_id = meta_path.parent.name
        body_path = FEATURES_DIR / feature_id / "install.bash"
        target_path = SRC_DIR / feature_id / "install.bash"

        if not body_path.exists():
            continue

        with meta_path.open(encoding="utf-8") as fh:
            meta = yaml.safe_load(fh)

        feature_name: str = meta.get("name", feature_id)
        options: dict = meta.get("options", {})
        if not isinstance(options, dict):
            options = {}
        dependencies: dict | None = meta.get("_dependencies")

        new_block = generate_block(feature_name, options, dependencies)
        new_block = _shfmt_format(new_block)

        if check_mode:
            if not target_path.exists():
                print(f"⛔ {feature_id}: assembled install.bash is missing in src/", file=sys.stderr)
                any_stale = True
                continue
            text = target_path.read_text(encoding="utf-8")
            end_pat = re.compile(r"^# END OF AUTOGENERATED BLOCK$", re.MULTILINE)
            m_end = end_pat.search(text)
            if m_end is None:
                print(
                    f"⛔ {feature_id}: '{MARKER_END}' marker missing in src/",
                    file=sys.stderr,
                )
                any_stale = True
                continue
            # Compare from file start to end of marker line (including its \n)
            current_block = text[: m_end.end() + 1]
            if current_block != new_block:
                print(f"⛔ {feature_id}: generated header is stale", file=sys.stderr)
                any_stale = True
            else:
                print(f"✅ {feature_id}: in sync", file=sys.stderr)
        else:
            changed, err = write_assembled(body_path, target_path, new_block)
            if err:
                print(f"⛔ {feature_id}: {err}", file=sys.stderr)
                any_error = True
            elif changed:
                print(f"✅ {feature_id}: assembled install.bash written", file=sys.stderr)
            else:
                print(f"✅ {feature_id}: install.bash unchanged", file=sys.stderr)

    if check_mode and any_stale:
        print("", file=sys.stderr)
        print(
            "⛔ Stale generated headers detected. Run: bash scripts/sync-src.sh",
            file=sys.stderr,
        )
        return 1

    if any_error:
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
