#!/usr/bin/env bash
# Unified test dispatcher.
#
# Usage:
#   bash .dev/scripts/test/run.sh unit    [--module <name>] [--filter <regex>] [--jobs <n>]
#   bash .dev/scripts/test/run.sh feature <feature>
#   bash .dev/scripts/test/run.sh linux   <feature> [--filter <scenario>]
#   bash .dev/scripts/test/run.sh macos   <feature> [--filter <scenario>]
#   bash .dev/scripts/test/run.sh dry-run
#   bash .dev/scripts/test/run.sh all
#
# Exit code: 0 if all selected tests pass, 1 if any fail.
set -euo pipefail

_SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$_SCRIPTS_DIR" rev-parse --show-toplevel)"

_usage() {
  cat << 'EOF'
Usage: bash .dev/scripts/test/run.sh <subcommand> [options]

Subcommands:
  unit    [--module <name>] [--filter <regex>] [--jobs <n>]
  feature <feature>
  linux   <feature> [--filter <scenario>]
  macos   <feature> [--filter <scenario>]
  dry-run
  all                        run unit and dry-run
EOF
}

if [[ $# -eq 0 ]]; then
  _usage >&2
  exit 1
fi

SUBCMD="$1"
shift

case "$SUBCMD" in
  unit)
    exec bash "${_SCRIPTS_DIR}/run-unit.sh" "$@"
    ;;
  feature)
    FEATURE="${1:?Usage: bash .dev/scripts/test/run.sh feature <feature>}"
    shift
    _rc=0
    # Build a virtual project root so the devcontainer CLI sees:
    #   <tmpdir>/src  → repo src/
    #   <tmpdir>/test/<feature> → test/features/<feature>/devcontainer/
    # Tracked test/**/scenarios.json stays unchanged; GITHUB_TOKEN is merged
    # into the copy by merge_github_token_into_scenarios.py.
    _WORK="$(mktemp -d "${TMPDIR:-/tmp}/devfeats-feature-test.XXXXXX")"
    trap 'rm -rf "${_WORK}"' EXIT
    ln -sfn "${REPO_ROOT}/src" "${_WORK}/src"
    mkdir -p "${_WORK}/test"
    for feat_dir in "${REPO_ROOT}/test/features"/*/; do
      feat="$(basename "$feat_dir")"
      [[ -d "${feat_dir}/devcontainer" ]] &&
        cp -a "${feat_dir}/devcontainer" "${_WORK}/test/${feat}"
    done
    python3 "${_SCRIPTS_DIR}/merge_github_token_into_scenarios.py" \
      "${_WORK}/test"
    devcontainer features test -f "$FEATURE" --skip-autogenerated \
      --project-folder "$_WORK" || _rc=$?
    bash "${_SCRIPTS_DIR}/run-linux.sh" "$FEATURE" || _rc=$?
    exit "$_rc"
    ;;
  linux)
    exec bash "${_SCRIPTS_DIR}/run-linux.sh" "$@"
    ;;
  macos)
    exec bash "${_SCRIPTS_DIR}/run-macos.sh" "$@"
    ;;
  dry-run)
    exec bash "${REPO_ROOT}/test/features/install-os-pkg/unit/run.sh" "$REPO_ROOT"
    ;;
  all)
    _rc=0
    bash "${_SCRIPTS_DIR}/run-unit.sh" || _rc=1
    bash "${REPO_ROOT}/test/features/install-os-pkg/unit/run.sh" "$REPO_ROOT" || _rc=1
    exit "$_rc"
    ;;
  --help | -h)
    _usage
    exit 0
    ;;
  *)
    echo "⛔ Unknown subcommand: '$SUBCMD'" >&2
    _usage >&2
    exit 1
    ;;
esac
