"""Install script generation for devcontainer features."""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from proman.const import export_profile_d, feat_share_dir
from proman.git import git_owner_repo

HEADER_END_MARKER = "# END OF AUTOGENERATED BLOCK"


class InstallScriptGenerator:
    """Generate install.bash header blocks from feature metadata."""

    def __init__(
        self,
        features_dirpath: Path,
        templates_dirpath: Path,
        repo_dirpath: Path,
    ) -> None:
        self._features_dirpath = features_dirpath
        self._templates = self._load_templates(templates_dirpath)
        self._repo_dirpath = repo_dirpath

    def generate(self, metadata: dict) -> dict[Path, str]:
        """Generate the full install.bash content for a feature.

        The generated content covers everything from the shebang (#!/usr/bin/env bash)
        through the argument-parsing block and default-variable initialisation, and is
        terminated by a single end marker:

            # END OF AUTOGENERATED BLOCK

        Everything after that marker in the file is hand-written implementation code
        and is never touched by this script.

        Options with ``type: array`` in metadata.yaml are treated as bash arrays:

        * CLI branch:      --flag <value>  (repeatable; each invocation appends)
        * env-var branch:  newline-delimited string split into an array
        * Defaults:        empty array  ()

        The ``type: array`` is serialised as ``type: string`` in
        devcontainer-feature.json (handled by metadata.py).
        """
        target_file = Path("install.bash")
        body_path = self._features_dirpath / metadata["id"] / target_file

        if not body_path.exists():
            return {}

        body = body_path.read_text(encoding="utf-8").strip("\n")

        feature_name: str = metadata["name"]
        options: dict = metadata["options"]
        dependencies: dict | None = metadata.get("_dependencies")
        prefix_groups: dict = metadata.get("_prefix_groups") or {}

        header = self._generate_block(
            feature_name, options, dependencies, prefix_groups, metadata["id"]
        )
        full_script = self._shfmt_format(f"{header}\n\n{body}\n")
        return {target_file: full_script}

    def _generate_block(
        self,
        feature_name: str,
        options: dict,
        dependencies: dict | None = None,
        prefix_groups: dict | None = None,
        feature_id: str = "",
    ) -> str:
        r"""Return the full generated content from shebang to END marker (inclusive).

        The returned string ends with ``# END OF AUTOGENERATED BLOCK\\n``.
        If ``_dependencies.run`` contains a ``base`` key, a ``_base_deps__install``
        call is emitted as the last statement before the end marker.
        If ``_dependencies.build`` is non-empty, dep-group helper functions are emitted.
        """
        run_deps: dict = (dependencies or {}).get("run") or {}
        build_deps: dict = (dependencies or {}).get("build") or {}
        parts = [
            self._render_template("preamble", FEATURE_NAME=feature_name),
            self._section_usage(options),
            self._section_arg_parse(options),
            self._section_defaults(options),
            self._section_feature_vars(feature_id),
            self._section_prefix_helpers(prefix_groups or {}, feature_id),
            self._section_validation(options),
            self._section_unexport(options),
            self._section_dep_helpers(run_deps, build_deps),
            self._section_base_deps_call(run_deps, build_deps),
            HEADER_END_MARKER,
        ]
        return "\n\n".join(p for p in parts if p)

    def _section_usage(self, options: dict) -> str:
        """Emit the __usage__() shell function."""
        entries: list[tuple[str, str, str, bool]] = []
        for key, opt in options.items():
            typ = opt["type"]
            flag_str = f"  {_opt_to_flag(key)} {_usage_type_hint(opt)}"
            has_default = "default" in opt
            default = opt.get("default", "")
            is_required = not has_default
            if typ == "boolean":
                disp_default = "true" if default else "false"
            elif typ == "array":
                disp_default = ""
            else:
                disp_default = (
                    str(default) if has_default and default is not None else ""
                )
            desc = _first_sentence(opt.get("description", ""))
            entries.append((flag_str, desc, disp_default, is_required))

        help_flag = "  -h, --help"
        col_width = max((len(f) for f, *_ in entries), default=len(help_flag))
        col_width = max(col_width, len(help_flag))

        lines = [
            "__usage__() {",
            "  cat << 'EOF'",
            "Usage: install.bash [OPTIONS]",
            "",
            "Options:",
        ]
        for (flag_str, desc, disp_default, is_required), _ in zip(
            entries,
            options.items(),
            strict=False,
        ):
            padding = " " * (col_width - len(flag_str) + 2)
            if is_required:
                desc_field = f"{desc} (required)"
            elif disp_default:
                desc_field = f'{desc} (default: "{disp_default}")'
            else:
                desc_field = desc
            lines.append(f"{flag_str}{padding}{desc_field}")
        help_padding = " " * (col_width - len(help_flag) + 2)
        lines.append(f"{help_flag}{help_padding}Show this help")
        lines.extend(["EOF", "  return", "}"])
        return "\n".join(lines)

    def _section_arg_parse(self, options: dict) -> str:
        """Emit the if/else/fi CLI-vs-env-var argument parsing block."""
        cli_inits: list[str] = []
        case_arms: list[str] = []
        env_reads: list[str] = []

        for key, opt in options.items():
            vname = _opt_to_var(key)
            typ = opt.get("type", "string")
            flag = _opt_to_flag(key)
            # Arrays are intentionally NOT pre-initialised: bash +=() on an unset
            # variable is safe, and pre-setting to () would fool the declare-based
            # default check.
            if typ != "array":
                if "default" not in opt:
                    cli_inits.append(f'  {vname}=""')
                else:
                    cli_inits.append(f"  {vname}={_shell_val(opt['default'], typ)}")
            if typ == "array":
                case_arms.append(
                    self._render_template(
                        "case_arm_array",
                        FLAG=flag,
                        VAR=vname,
                        KEY=key,
                    ),
                )
                env_reads.append(
                    self._render_template(
                        "env_read_array",
                        VAR=vname,
                        KEY=key,
                    ),
                )
            else:
                case_arms.append(
                    self._render_template(
                        "case_arm_scalar",
                        FLAG=flag,
                        VAR=vname,
                        KEY=key,
                    ),
                )
                env_reads.append(
                    self._render_template(
                        "env_read_scalar",
                        VAR=vname,
                        KEY=key,
                    ),
                )

        lines = [
            'if [ "$#" -gt 0 ]; then',
            '  logging__info "Script called with arguments: $*"',
        ]
        lines.extend(cli_inits)
        lines.extend(['  while [ "$#" -gt 0 ]; do', "    case $1 in"])
        lines.extend(case_arms)
        lines.extend(
            [
                "      -h | --help)",
                "        __usage__",
                "        exit 0",
                "        ;;",
                "      --*)",
                "        logging__error \"Unknown option: '${1}'\"",
                "        exit 1",
                "        ;;",
                "      *)",
                "        logging__error \"Unexpected argument: '${1}'\"",
                "        exit 1",
                "        ;;",
                "    esac",
                "  done",
                "else",
                '  logging__info "Script called with no arguments.'
                ' Read environment variables."',
            ],
        )
        lines.extend(env_reads)
        lines.append("fi")
        lines.append("logging__set_level")
        return "\n".join(lines)

    def _section_defaults(self, options: dict) -> str:
        """Emit the '# Apply defaults.' block."""
        blocks = ["# Apply defaults."]
        for key, opt in options.items():
            vname = _opt_to_var(key)
            typ = opt.get("type", "string")
            if "default" not in opt:
                continue
            if typ == "array":
                raw_default = opt["default"]
                if raw_default == "" or raw_default is None:
                    blocks.append(
                        self._render_template(
                            "default_array_empty",
                            VAR=vname,
                            KEY=key,
                        ),
                    )
                else:
                    # Embed the default as an ANSI-C quoted string so newlines
                    # are preserved.
                    escaped = (
                        str(raw_default)
                        .replace("\\", "\\\\")
                        .replace("'", "\\'")
                        .replace("\n", "\\n")
                        .replace("\r", "\\r")
                    )
                    disp = ", ".join(str(raw_default).splitlines())
                    blocks.append(
                        self._render_template(
                            "default_array_value",
                            VAR=vname,
                            ESCAPED=escaped,
                            KEY=key,
                            DISP=disp,
                        ),
                    )
            else:
                rhs = _shell_val(opt["default"], typ)
                if typ == "boolean":
                    disp = "true" if opt["default"] else "false"
                elif opt["default"] == "" or opt["default"] is None:
                    disp = ""
                else:
                    disp = str(opt["default"])
                blocks.append(
                    self._render_template(
                        "default_scalar",
                        VAR=vname,
                        RHS=rhs,
                        KEY=key,
                        DISP=disp,
                    ),
                )
        return "\n".join(blocks)

    def _section_validation(self, options: dict) -> str:
        """Emit required-argument checks and enum validation.

        Returns '' if neither applies.
        """
        required_opts = [(k, v) for k, v in options.items() if "default" not in v]
        enum_opts = [(k, v) for k, v in options.items() if v.get("enum")]
        if not required_opts and not enum_opts:
            return ""

        parts: list[str] = []
        if required_opts:
            checks: list[str] = []
            for key, opt in required_opts:
                vname = _opt_to_var(key)
                tpl = (
                    "validation_required_array"
                    if opt.get("type", "string") == "array"
                    else "validation_required_scalar"
                )
                checks.append(self._render_template(tpl, VAR=vname, KEY=key))
            parts.append("# Check required arguments.\n" + "\n".join(checks))

        if enum_opts:
            validations: list[str] = []
            for key, opt in enum_opts:
                vname = _opt_to_var(key)
                typ = opt.get("type", "string")
                values = [
                    item["value"] if isinstance(item, dict) else str(item)
                    for item in opt["enum"]
                ]
                expected = ", ".join(repr(v) if v == "" else v for v in values)
                pattern = " | ".join("''" if v == "" else v for v in values)
                tpl = (
                    "validation_enum_array"
                    if typ == "array"
                    else "validation_enum_scalar"
                )
                validations.append(
                    self._render_template(
                        tpl,
                        VAR=vname,
                        KEY=key,
                        PATTERN=pattern,
                        EXPECTED=expected,
                    ),
                )
            parts.append("# Validate enum options.\n" + "\n".join(validations))

        return "\n\n".join(parts)

    def _section_unexport(self, options: dict) -> str:
        """Emit the 'declare +x' unexport line for all scalar option variables."""
        scalar_vars = [
            _opt_to_var(k)
            for k, v in options.items()
            if v.get("type", "string") != "array"
        ]
        if not scalar_vars:
            return ""
        return "\n".join(
            [
                "# Unexport option variables — values remain accessible in this"
                " script but",
                "# are not inherited by child processes.",
                "declare +x " + " ".join(scalar_vars),
            ],
        )

    def _section_feature_vars(self, feature_id: str) -> str:
        """Emit feature-wide variables available to both the generated header and body.

        Emits three read-only variables:

        _FILES_DIR
            Path to the ``files/`` sub-directory bundled alongside this script.
            Formula: ``${_BASE_DIR}/files``.  Body scripts can reference bundled
            shell scripts, config templates, etc. without hard-coding a relative path.

        _FEAT_SHARE_DIR
            Canonical location under ``/usr/local/share/`` where this feature writes
            persistent artefacts (entrypoints, lifecycle hooks, runtime config files).
            Formula: ``/usr/local/share/<owner>/<repo>/<feature_id>``.  All body
            code that creates files on the container should use this variable instead
            of hard-coding a path.

        _EXPORT_PROFILE_D
            Canonical ``/etc/profile.d/`` drop-in filename for environment-export
            blocks.  Formula: ``<owner>-<repo>-<feature_id>-export-path.sh``.
            Every shell function that writes a profile.d drop-in should reference
            this variable so the feature uses exactly one consistent filename.
        """
        _owner, _repo = git_owner_repo()
        return "\n".join(
            [
                '_FILES_DIR="${_BASE_DIR}/files"',
                f'_FEAT_SHARE_DIR="{feat_share_dir(feature_id, _owner, _repo)}"',
                f'_EXPORT_PROFILE_D="{export_profile_d(feature_id, _owner, _repo)}"',
            ]
        )

    def _section_prefix_helpers(self, prefix_groups: dict, feature_id: str) -> str:
        """Emit prefix resolver, symlink, and export_path bash functions."""
        if not prefix_groups:
            return ""

        fn_blocks: list[str] = [
            "# ── prefix-group helpers (generated)"
            " ──────────────────────────────────────────────",
        ]
        all_fn_calls: list[str] = []
        resolver_calls: list[str] = []

        for group_id, group_cfg in prefix_groups.items():
            option_name: str | None = group_cfg.get("option_name")
            dir_symlink: bool = group_cfg.get("dir_symlink", False)
            skip_symlink: bool = group_cfg.get("skip_symlink", False)
            skip_export_path: bool = group_cfg.get("skip_export_path", False)
            default_root: str = group_cfg.get("default_root", "/usr/local")
            default_nonroot: str = group_cfg.get("default_nonroot", "${HOME}/.local")
            binname: str = group_cfg.get("bin", "")
            bin_dir: str = "bin"
            applies_when: list | None = group_cfg.get("_applies_when")

            opt_prefix = option_name or (f"{group_id}_prefix" if group_id else "prefix")
            opt_symlink = f"{group_id}_symlink" if group_id else "symlink"
            opt_export = f"{group_id}_export_path" if group_id else "export_path"

            var_prefix = _opt_to_var(opt_prefix)
            var_symlink = _opt_to_var(opt_symlink)
            var_export = _opt_to_var(opt_export)

            safe_id = group_id.replace("-", "_")
            if option_name:
                fn_resolve = f"resolve_{option_name}"
            elif group_id:
                fn_resolve = f"resolve_{safe_id}_prefix"
            else:
                fn_resolve = "resolve_prefix"
            fn_symlink = f"create_{safe_id}_symlink" if group_id else "create_symlink"
            fn_export = (
                f"export_{safe_id}_path_main" if group_id else "export_path_main"
            )

            guard_symlink = _make_applies_when_guard(applies_when, fn_symlink)
            guard_export = _make_applies_when_guard(applies_when, fn_export)

            optname_disp = option_name or opt_prefix

            # Resolver function
            fn_blocks.append(
                self._render_template(
                    "prefix_resolver",
                    FUNC_NAME=fn_resolve,
                    PREFIX_VAR=var_prefix,
                    OPTNAME=optname_disp,
                    RESOLUTION_BLOCK=_make_resolution_block(
                        var_prefix,
                        default_root,
                        default_nonroot,
                        group_cfg.get("platform_overrides", []),
                    ),
                )
            )

            # Symlink function (or no-op stub)
            if skip_symlink:
                fn_blocks.append(
                    f"# shellcheck disable=SC2329,SC2317\n{fn_symlink}() {{ return; }}"
                )
            elif dir_symlink:
                fn_blocks.append(
                    self._render_template(
                        "prefix_symlink_dir",
                        FUNC_NAME=fn_symlink,
                        PREFIX_VAR=var_prefix,
                        SYMLINK_VAR=var_symlink,
                        SYMLINK_OPT=opt_symlink,
                        DEFAULT_ROOT=default_root,
                        DEFAULT_NONROOT=default_nonroot,
                        APPLIES_WHEN_GUARD=guard_symlink,
                    )
                )
            else:
                fn_blocks.append(
                    self._render_template(
                        "prefix_symlink_bin",
                        FUNC_NAME=fn_symlink,
                        PREFIX_VAR=var_prefix,
                        SYMLINK_VAR=var_symlink,
                        SYMLINK_OPT=opt_symlink,
                        BIN=f"bin/{binname}",
                        DEFAULT_ROOT=default_root,
                        DEFAULT_NONROOT=default_nonroot,
                        APPLIES_WHEN_GUARD=guard_symlink,
                    )
                )

            # Export function (or no-op stub)
            if skip_export_path:
                fn_blocks.append(
                    f"# shellcheck disable=SC2329,SC2317\n{fn_export}() {{ return; }}"
                )
            else:
                marker = (
                    f"{binname} PATH ({feature_id})"
                    if binname
                    else f"PATH ({feature_id})"
                )
                fn_blocks.append(
                    self._render_template(
                        "prefix_export_path",
                        FUNC_NAME=fn_export,
                        PREFIX_VAR=var_prefix,
                        EXPORT_VAR=var_export,
                        EXPORT_OPT=opt_export,
                        BIN_DIR=bin_dir,
                        MARKER=marker,
                        APPLIES_WHEN_GUARD=guard_export,
                        RUNTIME_PATH_VAR=_opt_to_var("runtime_path"),
                    )
                )

            all_fn_calls.append(fn_symlink)
            all_fn_calls.append(fn_export)
            resolver_calls.append(fn_resolve)

        # _prefix_post_install__generated() aggregating all per-group calls
        post_install_body = "\n  ".join(all_fn_calls)
        fn_blocks.append(
            "# shellcheck disable=SC2329,SC2317\n"
            "_prefix_post_install__generated() {\n"
            f"  {post_install_body}\n"
            "  return\n"
            "}"
        )

        # _prefix_post_install() shadows the preamble no-op stub
        fn_blocks.append(
            "_prefix_post_install() {\n  _prefix_post_install__generated\n  return\n}"
        )

        # Inline resolver calls (run after defaults are applied)
        return "\n\n".join(fn_blocks) + "\n\n" + "\n".join(resolver_calls)

    def _section_dep_helpers(self, run_deps: dict, build_deps: dict) -> str:
        """Emit _<group>_deps__install() / _<group>_deps__cleanup() helper functions."""
        if not run_deps and not build_deps:
            return ""
        blocks = [
            "# ── dep-group helpers (generated)"
            " ──────────────────────────────────────────────",
        ]
        blocks.extend(
            self._render_template(
                "dep_helper_run",
                SAFE=gn.replace("-", "_"),
                GROUP=gn,
            )
            for gn in run_deps
        )
        blocks.extend(
            self._render_template(
                "dep_helper_build",
                SAFE=gn.replace("-", "_"),
                GROUP=gn,
            )
            for gn in build_deps
        )
        return "\n".join(blocks)

    def _section_base_deps_call(self, run_deps: dict, build_deps: dict) -> str:
        """Emit root-guarded _base_deps__install() calls: build first, then run."""
        parts = []
        if "base" in build_deps:
            parts.append(self._render_template("build_base_deps_call"))
        if "base" in run_deps:
            parts.append(self._render_template("base_deps_call"))
        return "\n\n".join(parts)

    def _shfmt_format(self, text: str) -> str:
        """Format a bash script fragment through shfmt, respecting .editorconfig.

        Writes to a temp file in the repo root so shfmt finds the .editorconfig
        style settings.  Returns *text* unchanged if shfmt is not on PATH.
        """
        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".sh",
            dir=self._repo_dirpath,
            delete=False,
            encoding="utf-8",
        ) as tmp:
            tmp.write(text)
            tmp_path = Path(tmp.name)
        try:
            result = subprocess.run(
                ["shfmt", "-w", str(tmp_path)],
                capture_output=True,
                check=False,
                cwd=self._repo_dirpath,
            )
            if result.returncode == 0:
                return tmp_path.read_text(encoding="utf-8")
            return text
        except FileNotFoundError:
            return text
        finally:
            tmp_path.unlink(missing_ok=True)

    def _render_template(self, name: str, **subs: str) -> str:
        """Load a shell snippet template and substitute @@KEY@@ placeholders."""
        template = self._templates[name]
        for key, val in subs.items():
            template = template.replace(f"@@{key}@@", val)
        return template

    @staticmethod
    def _load_templates(templates_dirpath: Path) -> dict[str, str]:
        templates = {}
        for template_path in templates_dirpath.glob("*.tmpl"):
            template_name = template_path.name.removesuffix(".sh.tmpl")
            templates[template_name] = template_path.read_text(encoding="utf-8").rstrip(
                "\n",
            )
        return templates


# ── Pure utilities ────────────────────────────────────────────────────────────


def _make_resolution_block(
    var_prefix: str,
    default_root: str,
    default_nonroot: str,
    platform_overrides: list[dict],
) -> str:
    """Build the shell if/elif/else resolution block for a prefix resolver.

    Without platform_overrides, emits a simple uid-based if/else.
    With overrides, prepends `os__match_spec` branches before the uid fallback.
    Each override dict must have ``when`` (mapping of key→value) and ``default``.
    ``default_root`` / ``default_nonroot`` within an override override ``default``
    per uid, mirroring the top-level default_root / default_nonroot semantics.
    """
    indent = "      "  # 6 spaces — inside case "")
    lines: list[str] = []
    first = True
    for override in platform_overrides:
        when: dict = override.get("when", {})
        default: str = override["default"]
        root_val: str = override.get("default_root", default)
        nonroot_val: str = override.get("default_nonroot", default)
        when_args = " ".join(f"{k}={v}" for k, v in when.items())
        keyword = "if" if first else "elif"
        lines.append(f"{indent}{keyword} os__match_spec {when_args}; then")
        if root_val == nonroot_val:
            lines.append(f'{indent}  {var_prefix}="{root_val}"')
        else:
            lines.append(f'{indent}  if [ "$(id -u)" = "0" ]; then')
            lines.append(f'{indent}    {var_prefix}="{root_val}"')
            lines.append(f"{indent}  else")
            lines.append(f'{indent}    {var_prefix}="{nonroot_val}"')
            lines.append(f"{indent}  fi")
        first = False
    uid_keyword = "elif" if platform_overrides else "if"
    lines.append(f'{indent}{uid_keyword} [ "$(id -u)" = "0" ]; then')
    lines.append(f'{indent}  {var_prefix}="{default_root}"')
    lines.append(f"{indent}else")
    lines.append(f'{indent}  {var_prefix}="{default_nonroot}"')
    lines.append(f"{indent}fi")
    return "\n".join(lines)


def _first_sentence(text: str) -> str:
    """Return the first non-empty line of a description."""
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped:
            return stripped
    return text.strip()


def _make_applies_when_guard(applies_when: list | None, func_name: str) -> str:
    """Generate a bash early-return guard string from an _applies_when condition list.

    Returns an indented guard block (with trailing newline) to be substituted for
    @@APPLIES_WHEN_GUARD@@, or an empty string if no condition is specified.

    Input format (same as _applies_when on options):
      [{varname: [val1, val2, ...]}]
    Only single-entry lists with a single key are supported (matches existing schema).
    """
    if not applies_when:
        return ""
    entry = applies_when[0]
    if not isinstance(entry, dict) or len(entry) != 1:
        return ""
    var_name, values = next(iter(entry.items()))
    var = _opt_to_var(var_name)
    if not values:
        return ""
    if len(values) == 1:
        val = values[0]
        return (
            f'  if [ "${{{var}}}" != "{val}" ]; then\n'
            f'    logging__fn_exit "{func_name}"\n'
            "    return 0\n"
            "  fi\n"
        )
    pattern = "|".join(str(v) for v in values)
    return (
        f'  case "${{{var}}}" in {pattern}) ;; *)\n'
        f'    logging__fn_exit "{func_name}"\n'
        "    return 0\n"
        "    ;;\n"
        "  esac\n"
    )


def _opt_to_var(key: str) -> str:
    """Convert a schema-validated option key to its installer env-var name.

    Option keys are constrained by features/metadata.schema.json to start with an
    ASCII letter and then contain only ASCII letters, digits, underscores, or
    hyphens. Given that contract, env-var generation is just uppercase plus
    '-' -> '_'.
    """
    return key.upper().replace("-", "_")


def _opt_to_flag(key: str) -> str:
    """Convert an option key to its --flag form."""
    return f"--{key}"


def _shell_val(default: object, typ: str) -> str:
    """Format a YAML default value as a shell assignment RHS (non-array types only)."""
    if typ == "boolean":
        return "true" if default else "false"
    if default == "" or default is None:
        return '""'
    return f'"{default}"'


def _usage_type_hint(opt: dict) -> str:
    """Return a concise type hint for the --help usage line."""
    typ = opt["type"]
    enum_raw = opt.get("enum", [])
    enum_values = [
        item["value"] if isinstance(item, dict) else str(item) for item in enum_raw
    ]
    if typ == "boolean":
        return "{true,false}"
    if typ == "array":
        if enum_values:
            return "{" + "|".join(enum_values) + "}  (repeatable)"
        return "<value>  (repeatable)"
    if enum_values:
        return "{" + "|".join(enum_values) + "}"
    return "<value>"
