"""Install script generation for devcontainer features."""

from __future__ import annotations

import re
import shlex
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import pyserials

from proman.config import load as load_config
from proman.feature_env import activation_profile_d_filename

# printf '%s' with an accidental real newline before the closing quote (db42a06b bug).
_SPLIT_PRINTF_PERCENT_S_RE = re.compile(r"printf '%s\r?\n\s+'", re.MULTILINE)

# Octal (600, 0644) or symbolic (+x, u+x) modes for _uri.chmod in metadata.
_URI_CHMOD_MODE_RE = re.compile(
    r"^([0-7]{3,4}|\+[rwxXstugo]+|[ugoa]*[-=+][rwxXstugo]+)$"
)


def _uri_chmod_mode(uri_cfg: bool | dict) -> str | None:
    """Return a chmod mode string from metadata ``_uri``, or None."""
    if not isinstance(uri_cfg, dict):
        return None
    if "chmod" in uri_cfg:
        mode = str(uri_cfg["chmod"])
        if not _URI_CHMOD_MODE_RE.match(mode):
            msg = (
                f"_uri.chmod must be octal (e.g. '600') or symbolic (e.g. '+x'); "
                f"got {mode!r}"
            )
            raise ValueError(msg)
        return mode
    if uri_cfg.get("chmod_exec"):
        return "+x"
    return None


def validate_generated_install_script(script: str) -> None:
    """Reject generated install.bash with broken bash escape sequences."""
    if _SPLIT_PRINTF_PERCENT_S_RE.search(script):
        msg = (
            "generated install.bash contains printf '%s' with a literal line break "
            "before the closing quote; fix Python codegen escaping (use '\\\\n')."
        )
        raise ValueError(msg)


@dataclass
class _DiscoveryParams:
    stem: str
    var_prefix: str
    bin_dir: str
    var_discovery: str
    var_runtime_path: str
    bins_str: str
    var_symlinks: str
    var_exports: str
    marker: str
    first_bin: str
    cmd_var: str
    skip_symlink: bool = False
    skip_exports: bool = False
    symlink_root: str = "/usr/local/bin"
    symlink_nonroot: str = field(default="${HOME}/.local/bin")


class InstallScriptGenerator:
    """Generate install.bash header blocks from feature metadata."""

    def __init__(self) -> None:
        self._config = load_config()
        self._features_dirpath = self._config.absolute_path("path.features")
        self._template = self._config.absolute_path(
            "path.install_script_template"
        ).read_text()
        self._repo_dirpath = self._config.root_path

    def generate(self, metadata: dict) -> dict[Path, str]:
        """Generate the full install.bash content for a feature.

        The generated content covers everything from the shebang (#!/usr/bin/env bash)
        through the argument-parsing block and default-variable initialisation, and is
        terminated by a single end marker:

            # END OF AUTOGENERATED BLOCK

        Everything after that marker in the file is hand-written implementation code
        and is never touched by this script.

        Options with ``type: array`` in metadata.yaml are treated as bash arrays:

        * CLI branch:      --flag <value>  (repeatable; each invocation appends)
        * env-var branch:  newline-delimited string split into an array
        * Defaults:        empty array  ()

        The ``type: array`` is serialised as ``type: string`` in
        devcontainer-feature.json (handled by metadata.py).
        """
        target_file = Path("install.bash")
        body_path = self._features_dirpath / metadata["id"] / target_file
        body = body_path.read_text(encoding="utf-8").strip("\n")
        header = self._generate_block(metadata=metadata)
        full_script = self._shfmt_format(f"{header}\n\n{body}\n")
        return {target_file: full_script}

    def _generate_block(self, metadata: dict) -> str:
        r"""Return the full generated content from shebang to END marker (inclusive).

        The returned string ends with ``# END OF AUTOGENERATED BLOCK\\n``.
        If ``_dependencies.run`` contains a ``base`` key, a ``_base_deps__install``
        call is emitted as the last statement before the end marker.
        If ``_dependencies.build`` is non-empty, dep-group helper functions are emitted.
        """
        feature_id: str = metadata["id"]
        options: dict = metadata["options"]
        prefix_groups: dict = metadata.get("_prefix_groups", {})

        prefix_resolver = self._generate_prefix_resolver_functions(
            prefix_groups, feature_id
        )
        prefix_var_names: frozenset[str] = frozenset(
            _opt_to_var(
                group_cfg.get("option_name")
                or (f"{group_id}_prefix" if group_id else "prefix")
            )
            for group_id, group_cfg in prefix_groups.items()
        )
        argparse = self._generate_argparse(options, prefix_var_names)
        if prefix_resolver["defaults"]:
            existing = argparse["defaults"]
            separator = "\n" if existing else ""
            argparse["defaults"] = existing + separator + prefix_resolver["defaults"]

        script_parts: dict[str, object] = {
            "usage_options": self._generate_usage_options(options),
            "argparse": argparse,
            "env_vars": self._generate_env_vars(metadata.get("_env_vars", {})),
            "prefix_resolver_functions": prefix_resolver["functions"],
            "prefix_post_install_body": self._generate_prefix_post_install_body(
                prefix_groups, feature_id
            ),
            "prefix_resolver_calls": self._generate_prefix_resolver_calls(
                prefix_groups
            ),
            "system_requirements_guard": self._generate_system_requirements_guard(
                metadata.get("_system_requirements", {})
            ),
        }
        template_data = metadata | {"_script": script_parts}
        try:
            script: str = pyserials.update.TemplateFiller().fill(
                data=template_data,
                template=self._template,
            )
        except Exception as e:
            raise ValueError(f"Error rendering template: {e}") from e

        validate_generated_install_script(script)
        return script

    @staticmethod
    def _generate_env_vars(env_vars: dict) -> dict[str, str]:
        """Emit one ``KEY="value"`` line per entry in metadata ``_env_vars``.

        Keys are emitted verbatim as bash variable names (they ARE the final names).
        Values are double-quoted so ``${HOME}`` and similar expansions still
        work at runtime.
        """
        if not isinstance(env_vars, dict) or not env_vars:
            return {"assignments": "", "unexports": ""}

        lines: list[str] = []
        var_names: list[str] = []
        for key in sorted(env_vars):
            value = env_vars[key]
            if not isinstance(value, str):
                msg = (
                    f"_env_vars['{key}'] must be a string after metadata fill"
                    f" (got {type(value).__name__})"
                )
                raise TypeError(msg)
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key}="{escaped}"')
            var_names.append(key)
        out = {
            "assignments": "\n".join(lines),
            "unexports": " ".join(var_names),
        }
        return out

    def _generate_usage_options(self, options: dict) -> str:
        """Emit the __usage__() shell function."""
        entries: list[tuple[str, str, str, bool]] = []
        for key, opt in options.items():
            typ = opt["type"]
            flag_str = f"  {_opt_to_flag(key)} {_usage_type_hint(opt)}"
            has_default = "default" in opt
            default = opt.get("default", "")
            is_required = not has_default
            if typ == "boolean":
                disp_default = "true" if default else "false"
            elif typ == "array":
                disp_default = ""
            else:
                disp_default = (
                    str(default) if has_default and default is not None else ""
                )
            desc = _first_sentence(opt.get("description", ""))
            entries.append((flag_str, desc, disp_default, is_required))
        entries.append(("  -h, --help", "Show this help and exit.", "", False))

        col_width = max((len(f) for f, *_ in entries))
        lines = []
        for (flag_str, desc, disp_default, is_required), _ in zip(
            entries,
            options.items(),
            strict=False,
        ):
            padding = " " * (col_width - len(flag_str) + 2)
            if is_required:
                desc_field = f"{desc} (required)"
            elif disp_default:
                desc_field = f'{desc} (default: "{disp_default}")'
            else:
                desc_field = desc
            lines.append(f"{flag_str}{padding}{desc_field}")

        return "\n".join(lines)

    def _generate_argparse(
        self, options: dict, prefix_var_names: frozenset[str] = frozenset()
    ) -> dict[str, str]:
        """Emit the if/else/fi CLI-vs-env-var argument parsing block."""
        cli_inits: list[str] = []
        case_arms: list[str] = []
        env_reads: list[str] = []

        case_arm_indent = 8
        env_read_indent = 4

        for key, opt in options.items():
            vname = _opt_to_var(key)
            typ = opt.get("type", "string")
            flag = _opt_to_flag(key)
            # Arrays are intentionally NOT pre-initialised: bash +=() on an unset
            # variable is safe, and pre-setting to () would fool the declare-based
            # default check.
            if typ != "array":
                if "default" not in opt:
                    cli_inits.append(f'    {vname}=""')
                else:
                    cli_inits.append(f"    {vname}={_shell_val(opt['default'], typ)}")
            if typ == "array":
                case_arms.append(
                    self._render_inline_template(
                        _ARGPARSE_CASE_ARM_ARRAY,
                        case_arm_indent,
                        flag=flag,
                        var=vname,
                        key=key,
                    ),
                )
                env_reads.append(
                    self._render_inline_template(
                        _ARGPARSE_ENV_READ_ARRAY,
                        env_read_indent,
                        var=vname,
                        key=key,
                    ),
                )
            else:
                case_arms.append(
                    self._render_inline_template(
                        _ARGPARSE_CASE_ARM_SCALAR,
                        case_arm_indent,
                        flag=flag,
                        var=vname,
                        key=key,
                    ),
                )
                env_reads.append(
                    self._render_inline_template(
                        _ARGPARSE_ENV_READ_SCALAR,
                        env_read_indent,
                        var=vname,
                        key=key,
                    ),
                )

        out = {
            "cli_inits": "\n".join(cli_inits),
            "case_arms": "\n".join(case_arms),
            "env_reads": "\n".join(env_reads),
            "defaults": self._generate_argparse_defaults(options, prefix_var_names),
            "normalize_arrays": self._generate_argparse_normalize_arrays(
                options, prefix_var_names
            ),
            "uri_resolution": self._generate_argparse_uri_resolution(
                options, prefix_var_names
            ),
            "validations": self._generate_argparse_validations(options),
            "unexports": self._generate_argparse_unexports(options),
        }
        return out

    def _generate_argparse_uri_resolution(
        self, options: dict, prefix_var_names: frozenset[str] = frozenset()
    ) -> str:
        """Emit URI resolution calls for options marked with `_uri`.

        Best practice: keep runtime logic in shell library functions. The
        generator emits only a compact, data-driven spec string consumed by
        `argparse__resolve_uri_options`.
        """
        spec_lines: list[str] = []
        for key, opt in options.items():
            vname = _opt_to_var(key)
            if vname in prefix_var_names:
                continue
            uri_cfg = opt.get("_uri", False)
            if not uri_cfg:
                continue
            typ = opt.get("type", "string")
            chmod_mode = _uri_chmod_mode(uri_cfg) if isinstance(uri_cfg, dict) else ""
            spec_lines.append(f"{key}\t{vname}\t{typ}\t{chmod_mode}")

        if not spec_lines:
            return ""

        def _escape_ansi_c(s: str) -> str:
            # Escape content for embedding inside bash ANSI-C $'...' strings.
            # Note: we intentionally do NOT escape the "\\n" record separators here;
            # we escape each line first, then join with "\\n" so separators remain
            # a bash newline escape (not a literal backslash-n).
            return s.replace("\\", "\\\\").replace("'", "\\'")

        spec_literal = "\\n".join(_escape_ansi_c(line) for line in spec_lines)
        blocks = [
            f"_DF_URI_SPECS=$'{spec_literal}'",
            'argparse__resolve_uri_options "${_DF_URI_SPECS}"',
            "unset _DF_URI_SPECS",
        ]
        return "\n".join(blocks).strip()

    def _generate_argparse_defaults(
        self, options: dict, prefix_var_names: frozenset[str] = frozenset()
    ) -> str:
        """Emit the '# Apply defaults.' block."""
        blocks = []
        dynamic_blocks = []
        for key, opt in options.items():
            vname = _opt_to_var(key)
            if vname in prefix_var_names:
                continue
            typ = opt.get("type", "string")
            if "default" not in opt:
                continue
            if typ == "array":
                raw_default = opt["default"]
                if raw_default == "" or raw_default is None:
                    blocks.append(f"argparse__default_array {vname}")
                else:
                    # Embed the default as an ANSI-C quoted string so newlines
                    # are preserved.
                    escaped = (
                        str(raw_default)
                        .replace("\\", "\\\\")
                        .replace("'", "\\'")
                        .replace("\n", "\\n")
                        .replace("\r", "\\r")
                    )
                    blocks.append(f"argparse__default_array_value {vname} $'{escaped}'")
            else:
                rhs = _shell_val(opt["default"], typ)
                blocks.append(f"argparse__default {vname} {rhs}")
                dynamic_default = opt.get("_default")
                if dynamic_default is not None:
                    dynamic_blocks.append(
                        self._render_inline_template(
                            _ARGPARSE_DEFAULT_DYNAMIC,
                            2,
                            var=vname,
                            rhs=f'"{dynamic_default}"',
                            key=key,
                        ),
                    )

        return "\n".join(blocks + dynamic_blocks)

    def _generate_argparse_normalize_arrays(
        self, options: dict, prefix_var_names: frozenset[str] = frozenset()
    ) -> str:
        """Emit trim/filter calls for every array option after defaults are applied."""
        blocks: list[str] = []
        for key, opt in options.items():
            if opt.get("type") != "array":
                continue
            vname = _opt_to_var(key)
            if vname in prefix_var_names:
                continue
            blocks.append(f"argparse__normalize_array {vname}")
        return "\n".join(blocks)

    def _generate_argparse_validations(self, options: dict) -> str:
        """Emit boolean, integer, enum, and path validation blocks.

        Returns '' if none apply.
        """
        validations: list[str] = []
        for key, opt in options.items():
            vname = _opt_to_var(key)
            typ = opt.get("type", "string")
            if typ == "boolean":
                validations.append(f"argparse__validate_bool {vname}")
            elif typ == "integer":
                validations.append(f"argparse__validate_integer {vname}")
                minimum = opt.get("_minimum")
                if minimum is not None:
                    validations.append(
                        f"argparse__validate_integer_min {vname} {minimum}"
                    )
                maximum = opt.get("_maximum")
                if maximum is not None:
                    validations.append(
                        f"argparse__validate_integer_max {vname} {maximum}"
                    )
            elif opt.get("enum"):
                values = [
                    item["value"] if isinstance(item, dict) else str(item)
                    for item in opt["enum"]
                ]
                fn = (
                    "argparse__validate_enum_array"
                    if typ == "array"
                    else "argparse__validate_enum"
                )
                values_str = " ".join(shlex.quote(v) for v in values)
                validations.append(f"{fn} {vname} {values_str}")
            path_spec = opt.get("_path")
            if path_spec is None:
                continue
            ops = [path_spec] if isinstance(path_spec, str) else path_spec
            if typ == "array":
                for op in ops:
                    validations.append(
                        f'argparse__validate_path_array {vname} "{op}"'
                    )
            else:
                for op in ops:
                    validations.append(f'argparse__validate_path {vname} "{op}"')
        return "\n".join(validations)

    def _generate_argparse_unexports(self, options: dict) -> str:
        """Emit the 'declare -g +x' unexport line for all scalar option variables."""
        scalar_vars = [
            _opt_to_var(k)
            for k, v in options.items()
            if v.get("type", "string") != "array"
        ]
        return " ".join(scalar_vars)

    def _generate_prefix_resolver_functions(
        self, prefix_groups: dict, feature_id: str
    ) -> dict[str, str]:
        """Emit per-group resolver functions, activation stubs, and argparse dynamic defaults."""
        if not prefix_groups:
            return {"functions": "", "defaults": ""}

        fn_blocks: list[str] = []
        default_blocks: list[str] = []

        for group_id, group_cfg in prefix_groups.items():
            prefix_cfg: dict = group_cfg.get("prefix", {})
            activation_cfg: dict | None = group_cfg.get("activation")

            option_name: str | None = group_cfg.get("option_name")
            default_root: str = prefix_cfg.get("root", "/usr/local")
            default_nonroot: str = prefix_cfg.get("nonroot", "${HOME}/.local")

            stem = option_name or (f"{group_id}_prefix" if group_id else "prefix")
            var_prefix = _opt_to_var(stem)

            safe_id = group_id.replace("-", "_")
            if option_name:
                fn_resolve = f"resolve_{option_name}"
            elif group_id:
                fn_resolve = f"resolve_{safe_id}_prefix"
            else:
                fn_resolve = "resolve_prefix"
            fn_activation_snippet = f"{stem}_activation_snippet"

            _scope_block = (
                _TMPL_SCOPE_SNAPSHOT.format(var_prefix=var_prefix)
                if activation_cfg
                else ""
            )

            groups_args = _make_resolver_groups(
                prefix_cfg.get("platform_overrides", []),
                default_root,
                default_nonroot,
            )
            fn_blocks.append(
                self._render_inline_template(
                    _TMPL_PREFIX_RESOLVER_SIMPLE,
                    0,
                    func_name=fn_resolve,
                    prefix_var=var_prefix,
                    opt_name=stem,
                    scope_block=_scope_block,
                )
            )

            default_blocks.append(
                self._render_inline_template(
                    _ARGPARSE_DEFAULT_DYNAMIC,
                    2,
                    var=var_prefix,
                    rhs=f'"$(users__first_writeable_path \\\n  {groups_args})" || exit 1',
                    key=stem,
                )
            )

            if activation_cfg:
                fn_blocks.append(
                    self._render_inline_template(
                        _TMPL_ACTIVATION_STUB, 0, func_name=fn_activation_snippet
                    )
                )

        return {
            "functions": "\n\n".join(fn_blocks),
            "defaults": "\n".join(default_blocks),
        }

    def _generate_prefix_post_install_body(
        self, prefix_groups: dict, feature_id: str
    ) -> str:
        """Emit the body of _prefix_post_install__generated()."""
        if not prefix_groups:
            return ""

        post_install_blocks: list[str] = []
        # cmd_var → first_bin; needs bare-binary fallback when guarded.
        guarded_cmd_vars: dict[str, str] = {}

        for group_id, group_cfg in prefix_groups.items():
            prefix_cfg: dict = group_cfg.get("prefix", {})
            symlink_cfg: dict = group_cfg.get("symlink", {})
            exports_cfg: dict = group_cfg.get("exports", {})
            activation_cfg: dict | None = group_cfg.get("activation")

            option_name: str | None = group_cfg.get("option_name")
            skip_symlink: bool = symlink_cfg.get("skip", False)
            skip_exports: bool = exports_cfg.get("skip", False)
            symlink_root: str = symlink_cfg.get("root", "/usr/local/bin")
            symlink_nonroot: str = symlink_cfg.get("nonroot", "${HOME}/.local/bin")
            bins: list[str] = prefix_cfg.get("bins", [])
            bin_dir: str = prefix_cfg.get("bin_dir", "bin")
            applies_when: list | None = group_cfg.get("applies_when")

            stem = option_name or (f"{group_id}_prefix" if group_id else "prefix")
            opt_prefix = stem
            opt_symlinks = f"{stem}_symlinks"
            opt_exports = f"{stem}_exports"
            opt_discovery = f"{stem}_discovery"

            var_prefix = _opt_to_var(opt_prefix)
            var_symlinks = _opt_to_var(opt_symlinks)
            var_exports = _opt_to_var(opt_exports)
            var_discovery = _opt_to_var(opt_discovery)

            fn_activation_snippet = f"{stem}_activation_snippet"
            var_activations = _opt_to_var(f"{stem}_activations")
            activation_marker = f"{stem} activation ({feature_id})"
            activation_profile_d = activation_profile_d_filename(feature_id, stem)

            first_bin = bins[0] if bins else ""
            bins_str = " ".join(bins) if bins else ""
            marker = (
                f"{first_bin} PATH ({feature_id})"
                if first_bin
                else f"PATH ({feature_id})"
            )
            if group_id:
                cmd_var = f"_DF_EXPECTED_CMD_{group_id.upper().replace('-', '_')}"
            else:
                cmd_var = "_DF_EXPECTED_CMD"

            # Discovery block
            # Skip entirely when both symlinks and exports are disabled — the call
            # would be a no-op side-effect-wise, and the computed cmd path
            # (prefix/bin/name) would be wrong for installs like nvm that don't
            # place binaries directly under the prefix/bin directory.
            if not (skip_symlink and skip_exports):
                discovery_block = self._build_discovery_block(
                    _DiscoveryParams(
                        stem=stem,
                        var_prefix=var_prefix,
                        bin_dir=bin_dir,
                        var_discovery=var_discovery,
                        var_runtime_path=_opt_to_var("runtime_path"),
                        bins_str=bins_str,
                        var_symlinks=var_symlinks,
                        var_exports=var_exports,
                        marker=marker,
                        first_bin=first_bin,
                        cmd_var=cmd_var,
                        skip_symlink=skip_symlink,
                        skip_exports=skip_exports,
                        symlink_root=symlink_root,
                        symlink_nonroot=symlink_nonroot,
                    )
                )
                post_install_blocks.append(
                    _wrap_applies_when(applies_when, discovery_block)
                )
                if applies_when and first_bin and cmd_var not in guarded_cmd_vars:
                    guarded_cmd_vars[cmd_var] = first_bin

            if activation_cfg:
                activation_block = self._render_inline_template(
                    _TMPL_PREFIX_ACTIVATION,
                    0,
                    stem=stem,
                    marker=activation_marker,
                    profile_d_name=activation_profile_d,
                    snippet_func=fn_activation_snippet,
                    activations_var=var_activations,
                    prefix_var=var_prefix,
                )
                post_install_blocks.append(
                    _wrap_applies_when(applies_when, activation_block)
                )

            write_group_cfg: dict | None = group_cfg.get("write_group")
            if write_group_cfg is not None:
                if group_id:
                    wg_key = f"{group_id}_write_group"
                    wu_key = f"{group_id}_write_users"
                else:
                    wg_key = "write_group"
                    wu_key = "write_users"
                wg_var = _opt_to_var(wg_key)
                wu_var = _opt_to_var(wu_key)
                owner_var_name: str = write_group_cfg.get("owner_var", "")
                owner_expr = (
                    f'"${{{owner_var_name}}}"' if owner_var_name else '"$(id -nu)"'
                )
                write_group_block = self._render_inline_template(
                    _TMPL_WRITE_GROUP,
                    0,
                    wu_var=wu_var,
                    wg_var=wg_var,
                    var_prefix=var_prefix,
                    owner_expr=owner_expr,
                )
                post_install_blocks.append(
                    _wrap_applies_when(applies_when, write_group_block)
                )

        # Bare-binary fallbacks ensure cmd-vars are always set even when an
        # applies_when guard prevented the discovery block from running.
        # The := operator makes each line a no-op when discovery already set the var.
        for _cv, _fb in guarded_cmd_vars.items():
            post_install_blocks.append(f': "${{{_cv}:={_fb}}}"')

        return "\n\n".join(post_install_blocks)

    def _generate_prefix_resolver_calls(self, prefix_groups: dict) -> str:
        """Emit the inline resolver call lines."""
        if not prefix_groups:
            return ""

        resolver_calls: list[str] = []
        for group_id, group_cfg in prefix_groups.items():
            option_name: str | None = group_cfg.get("option_name")
            safe_id = group_id.replace("-", "_")
            if option_name:
                fn_resolve = f"resolve_{option_name}"
            elif group_id:
                fn_resolve = f"resolve_{safe_id}_prefix"
            else:
                fn_resolve = "resolve_prefix"
            resolver_calls.append(fn_resolve)

        return "\n".join(resolver_calls)

    def _generate_system_requirements_guard(self, sys_req: dict) -> str:
        """Emit platform and root-privilege guards from _system_requirements."""
        if not sys_req:
            return "return 0  # No system requirements."

        platforms: list[dict] | None = sys_req.get("platforms")
        root = sys_req.get("root", False)

        blocks: list[str] = []

        if platforms:
            spec_args = _match_specs_to_args(platforms)
            blocks.append(f"sys_req__require_platform {spec_args}")

        if root is True:
            blocks.append("sys_req__require_root")
        elif isinstance(root, list) and root:
            spec_args = _match_specs_to_args(root)
            blocks.append(f"sys_req__require_root {spec_args}")

        return "\n\n".join(blocks)

    def _shfmt_format(self, text: str) -> str:
        """Format a bash script fragment through shfmt, respecting .editorconfig.

        Writes to a temp file in the repo root so shfmt finds the .editorconfig
        style settings.  Returns *text* unchanged if shfmt is not on PATH.
        """
        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".sh",
            dir=self._repo_dirpath,
            delete=False,
            encoding="utf-8",
        ) as tmp:
            tmp.write(text)
            tmp_path = Path(tmp.name)
        try:
            result = subprocess.run(
                ["shfmt", "-w", str(tmp_path)],
                capture_output=True,
                check=False,
                cwd=self._repo_dirpath,
            )
            if result.returncode == 0:
                return tmp_path.read_text(encoding="utf-8")
            return text
        except FileNotFoundError:
            return text
        finally:
            tmp_path.unlink(missing_ok=True)

    @staticmethod
    def _render_inline_template(template: str, indent: int, **subs: str) -> str:
        """Substitute {key} placeholders in a template, indenting all lines."""
        filled = template.format(**subs)
        indentation = " " * indent
        return "\n".join(
            f"{indentation}{line}" if line.strip() else line
            for line in filled.splitlines()
        ).strip()

    @staticmethod
    def _build_discovery_block(p: _DiscoveryParams) -> str:
        if p.skip_symlink and p.skip_exports:
            comment_suffix = " (symlinks and exports disabled)"
        elif p.skip_symlink:
            comment_suffix = " (no symlinks)"
        else:
            comment_suffix = ""
        args: list[str] = [
            f'--prefix "${{{p.var_prefix}}}"',
            f'--bin-dir "{p.bin_dir}"',
            f'--discovery "${{{p.var_discovery}}}"',
            f'--runtime-path "${{{p.var_runtime_path}}}"',
        ]
        if not p.skip_symlink:
            args += [f'--bins "{p.bins_str}"', f'--symlinks-ref "{p.var_symlinks}"']
            if p.symlink_root != "/usr/local/bin":
                args.append(f'--symlink-root "{p.symlink_root}"')
            if p.symlink_nonroot != "${HOME}/.local/bin":
                args.append(f'--symlink-nonroot "{p.symlink_nonroot}"')
        if not p.skip_exports:
            args += [
                f'--exports-ref "{p.var_exports}"',
                f'--marker "{p.marker}"',
                '--profile-d "${_FEAT_PROFILE_D_FILE}"',
            ]
        args += [f'--bin "{p.first_bin}"', f'--cmd-var "{p.cmd_var}"']
        if p.skip_symlink:
            args.append("--no-symlinks")
        if p.skip_exports:
            args.append("--no-exports")
        fn_name = f"{p.stem}_discovery"
        args_lines = "\n".join(
            f"  {arg} \\" if i < len(args) - 1 else f"  {arg}"
            for i, arg in enumerate(args)
        )
        return InstallScriptGenerator._render_inline_template(
            _TMPL_DISCOVERY_BLOCK,
            0,
            stem=p.stem,
            comment_suffix=comment_suffix,
            fn_name=fn_name,
            args_lines=args_lines,
        )


# ── Pure utilities ────────────────────────────────────────────────────────────


def _match_specs_to_args(specs: list[dict]) -> str:
    """Build the shell arg list for sys_req__require_* functions (leading -- per group)."""
    parts: list[str] = []
    for spec in specs:
        parts.append("--")
        parts.extend(f"{k}={v}" for k, v in spec.items())
    return " ".join(parts)


def _make_resolver_groups(
    platform_overrides: list[dict],
    default_root: str,
    default_nonroot: str,
) -> str:
    """Build the '--'-separated group arg string for users__resolve_prefix.

    Each platform_overrides entry becomes '-- key=val... root [nonroot]'.
    The unconditional fallback ('-- root nonroot') is always appended last.
    When root == nonroot within an entry, only one path is emitted (single candidate).
    """
    groups: list[str] = []
    for override in platform_overrides:
        when_args = " ".join(f"{k}={v}" for k, v in override.get("when", {}).items())
        default: str = override["default"]
        root_val: str = override.get("root", default)
        nonroot_val: str = override.get("nonroot", default)
        paths = (
            f'"{root_val}"'
            if root_val == nonroot_val
            else f'"{root_val}" "{nonroot_val}"'
        )
        groups.append(f"-- {when_args} {paths}" if when_args else f"-- {paths}")
    fallback = f'"{default_root}"'
    if default_root != default_nonroot:
        fallback += f' "{default_nonroot}"'
    groups.append(f"-- {fallback}")
    return " \\\n  ".join(groups)


def _first_sentence(text: str) -> str:
    """Return the first non-empty line of a description."""
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped:
            return stripped
    return text.strip()


def _wrap_applies_when(applies_when: list | None, block: str) -> str:
    """Wrap a shell block in a positive if/case guard from an applies_when condition.

    Returns the block unchanged when applies_when is absent or unparseable.
    Input format: [{varname: [val1, val2, ...]}]
    """
    if not applies_when:
        return block
    entry = applies_when[0]
    if not isinstance(entry, dict) or len(entry) != 1:
        return block
    var_name, values = next(iter(entry.items()))
    var = _opt_to_var(var_name)
    if not values:
        return block
    if len(values) == 1:
        return f'if [ "${{{var}}}" = "{values[0]}" ]; then\n{block}\nfi'
    pattern = " | ".join(str(v) for v in values)
    return f'case "${{{var}}}" in {pattern})\n{block}\n;;\nesac'


def _opt_to_var(key: str) -> str:
    """Convert a schema-validated option key to its installer env-var name.

    Option keys are constrained by features/metadata.schema.json to start with an
    ASCII letter and then contain only ASCII letters, digits, underscores, or
    hyphens. Given that contract, env-var generation is just uppercase plus
    '-' -> '_'.
    """
    return key.upper().replace("-", "_")


def _opt_to_flag(key: str) -> str:
    """Convert an option key to its --flag form."""
    return f"--{key}"


def _shell_val(default: object, typ: str) -> str:
    """Format a YAML default value as a shell assignment RHS (non-array types only)."""
    if typ == "boolean":
        return "true" if default else "false"
    if default == "" or default is None:
        return '""'
    return f'"{default}"'


def _usage_type_hint(opt: dict) -> str:
    """Return a concise type hint for the --help usage line."""
    typ = opt["type"]
    enum_raw = opt.get("enum", [])
    enum_values = [
        item["value"] if isinstance(item, dict) else str(item) for item in enum_raw
    ]
    if typ == "boolean":
        return "{true,false}"
    if typ == "integer":
        minimum = opt.get("_minimum")
        maximum = opt.get("_maximum")
        if minimum is not None or maximum is not None:
            lo = str(minimum) if minimum is not None else ""
            hi = str(maximum) if maximum is not None else ""
            return f"<integer {lo}..{hi}>"
        return "<integer>"
    if typ == "array":
        if enum_values:
            return "{" + "|".join(enum_values) + "}  (repeatable)"
        return "<value>  (repeatable)"
    if enum_values:
        return "{" + "|".join(enum_values) + "}"
    return "<value>"


_ARGPARSE_CASE_ARM_ARRAY = """
{flag})
shift
{var}+=("$1")
logging__read "Argument '{key}': '$1'"
shift
;;
"""

_ARGPARSE_CASE_ARM_SCALAR = """
{flag})
shift
{var}="$1"
logging__read "Argument '{key}': '$1'"
shift
;;
"""

_ARGPARSE_ENV_READ_ARRAY = """
if [ "${{{var}+defined}}" ]; then
  if [ -n "${{{var}-}}" ]; then
    argparse__split_lines {var} "${{{var}}}"
    for _item in "${{{var}[@]}}"; do
    logging__read "Argument '{key}': '$_item'"
    done
  else
    {var}=()
  fi
fi
"""

_ARGPARSE_ENV_READ_SCALAR = """
[ "${{{var}+defined}}" ] && logging__read "Argument '{key}': '${{{var}}}'"
"""

_ARGPARSE_DEFAULT_DYNAMIC = """
[ -n "${{{var}-}}" ] || {{
  {var}={rhs}
  logging__info "Argument '{key}' dynamic default resolved to '${{{var}}}'."
}}
"""

_TMPL_PREFIX_RESOLVER_SIMPLE = """
# shellcheck disable=SC2329,SC2317
{func_name}() {{
  logging__fn_entry "{func_name}"
  users__can_write "${{{prefix_var}}}" || {{
    logging__error "Option '{opt_name}': '${{{prefix_var}}}' is not writable."
    exit 1
  }}
  logging__info "Option '{opt_name}' resolved to '${{{prefix_var}}}'."{scope_block}
  logging__fn_exit "{func_name}"
  return
}}
"""

_TMPL_ACTIVATION_STUB = """
# shellcheck disable=SC2329,SC2317
{func_name}() {{ return 1; }}
"""

_TMPL_SCOPE_SNAPSHOT = (
    "\n"
    "  # Activation scope snapshot: captured before write_group\n"
    "  # chown can alter path ownership. Consumed by\n"
    "  # _prefix_post_install.\n"
    "  # shellcheck disable=SC2034\n"
    '  {var_prefix}_SCOPE="$(users__is_user_path'
    ' "${{{var_prefix}}}" && printf user || printf system)"'
)

_TMPL_WRITE_GROUP = """
_wargs=()
if [[ "${{#{wu_var}[@]}}" -gt 0 ]]; then
  _wargs=(--current false --remote false --container false)
  for _u in "${{{wu_var}[@]}}"; do _wargs+=(--user "$_u"); done
fi
mapfile -t _write_users < <(users__resolve_list "${{_wargs[@]}}")
if [[ -n "${{{wg_var}:-}}" ]]; then
  users__set_write_permissions "${{{var_prefix}}}" {owner_expr} "${{{wg_var}}}" "${{_write_users[@]}}"
fi
"""

_TMPL_DISCOVERY_BLOCK = """
# -- discovery: {stem}{comment_suffix} --
logging__fn_entry "{fn_name}"
shell__run_prefix_discovery \\
{args_lines}
logging__fn_exit "{fn_name}"
"""


_TMPL_PREFIX_ACTIVATION = """
# -- activation: {stem} --
_act_home_arg=""
if [ "${{{prefix_var}_SCOPE}}" = "user" ]; then
  _act_home_arg="$(users__home_of_path_owner "${{{prefix_var}}}")"
fi
shell__write_activation_snippets \
  --scope "${{{prefix_var}_SCOPE}}" \
  ${{_act_home_arg:+--home "${{_act_home_arg}}"}} \
  "{marker}" "{profile_d_name}" "{snippet_func}" \
  "${{{activations_var}[@]}}"
unset _act_home_arg
"""
