"""Install script generation for devcontainer features."""

from __future__ import annotations

import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from proman.const import (
    INSTALL_BASH_HEADER_END_MARKER,
    export_profile_d,
    feat_share_dir,
)
from proman.git import git_owner_repo


@dataclass
class _DiscoveryParams:
    stem: str
    var_prefix: str
    bin_dir: str
    var_discovery: str
    var_runtime_path: str
    bins_str: str
    var_symlinks: str
    var_exports: str
    marker: str
    first_bin: str
    cmd_var: str
    skip_symlink: bool = False
    skip_exports: bool = False
    symlink_root: str = "/usr/local/bin"
    symlink_nonroot: str = field(default="${HOME}/.local/bin")


class InstallScriptGenerator:
    """Generate install.bash header blocks from feature metadata."""

    def __init__(
        self,
        features_dirpath: Path,
        templates_dirpath: Path,
        repo_dirpath: Path,
    ) -> None:
        self._features_dirpath = features_dirpath
        self._templates = self._load_templates(templates_dirpath)
        self._repo_dirpath = repo_dirpath

    def generate(self, metadata: dict) -> dict[Path, str]:
        """Generate the full install.bash content for a feature.

        The generated content covers everything from the shebang (#!/usr/bin/env bash)
        through the argument-parsing block and default-variable initialisation, and is
        terminated by a single end marker:

            # END OF AUTOGENERATED BLOCK

        Everything after that marker in the file is hand-written implementation code
        and is never touched by this script.

        Options with ``type: array`` in metadata.yaml are treated as bash arrays:

        * CLI branch:      --flag <value>  (repeatable; each invocation appends)
        * env-var branch:  newline-delimited string split into an array
        * Defaults:        empty array  ()

        The ``type: array`` is serialised as ``type: string`` in
        devcontainer-feature.json (handled by metadata.py).
        """
        target_file = Path("install.bash")
        body_path = self._features_dirpath / metadata["id"] / target_file

        if not body_path.exists():
            return {}

        body = body_path.read_text(encoding="utf-8").strip("\n")
        header = self._generate_block(metadata=metadata)
        full_script = self._shfmt_format(f"{header}\n\n{body}\n")
        return {target_file: full_script}

    def _generate_block(self, metadata: dict) -> str:
        r"""Return the full generated content from shebang to END marker (inclusive).

        The returned string ends with ``# END OF AUTOGENERATED BLOCK\\n``.
        If ``_dependencies.run`` contains a ``base`` key, a ``_base_deps__install``
        call is emitted as the last statement before the end marker.
        If ``_dependencies.build`` is non-empty, dep-group helper functions are emitted.
        """
        feature_id: str = metadata["id"]
        options: dict = metadata["options"]
        dependencies: dict = metadata.get("_dependencies", {})
        prefix_groups: dict = metadata.get("_prefix_groups", {})
        installer_dir_flag: bool = bool(metadata.get("_installer_dir", False))
        run_deps: dict = dependencies.get("run", {})
        build_deps: dict = dependencies.get("build", {})
        _owner, _repo = git_owner_repo()
        parts = [
            self._render_template(
                "preamble",
                FEATURE_ID=feature_id,
                FEATURE_VERSION=metadata["version"],
                FEATURE_NAME=metadata["name"],
                FEATURE_SHARE_DIR=feat_share_dir(feature_id, _owner, _repo),
                FEATURE_PROFILE_D_FILE=export_profile_d(feature_id, _owner, _repo),
            ),
            self._section_usage(options),
            self._section_arg_parse(options),
            self._section_defaults(options),
            self._section_installer_dir_init(
                installer_dir_flag=installer_dir_flag,
                feature_id=feature_id,
            ),
            self._section_prefix_helpers(prefix_groups, feature_id),
            self._section_validation(options),
            self._section_unexport(options),
            self._section_dep_helpers(run_deps, build_deps),
            self._section_base_deps_call(run_deps, build_deps),
            INSTALL_BASH_HEADER_END_MARKER,
        ]
        return "\n\n".join(p for p in parts if p)

    def _section_installer_dir_init(
        self, *, installer_dir_flag: bool, feature_id: str
    ) -> str:
        """Emit INSTALLER_DIR auto-init snippet when _installer_dir is true."""
        if not installer_dir_flag:
            return ""
        return (
            "# Auto-initialize INSTALLER_DIR to a private temporary directory"
            " when not set.\n"
            f'[ -z "${{INSTALLER_DIR:-}}" ] && '
            f'INSTALLER_DIR="$(file__mktmpdir "install-{feature_id}")"'
        )

    def _section_usage(self, options: dict) -> str:
        """Emit the __usage__() shell function."""
        entries: list[tuple[str, str, str, bool]] = []
        for key, opt in options.items():
            typ = opt["type"]
            flag_str = f"  {_opt_to_flag(key)} {_usage_type_hint(opt)}"
            has_default = "default" in opt
            default = opt.get("default", "")
            is_required = not has_default
            if typ == "boolean":
                disp_default = "true" if default else "false"
            elif typ == "array":
                disp_default = ""
            else:
                disp_default = (
                    str(default) if has_default and default is not None else ""
                )
            desc = _first_sentence(opt.get("description", ""))
            entries.append((flag_str, desc, disp_default, is_required))

        help_flag = "  -h, --help"
        col_width = max((len(f) for f, *_ in entries), default=len(help_flag))
        col_width = max(col_width, len(help_flag))

        lines = [
            "__usage__() {",
            "  cat << 'EOF'",
            "Usage: install.bash [OPTIONS]",
            "",
            "Options:",
        ]
        for (flag_str, desc, disp_default, is_required), _ in zip(
            entries,
            options.items(),
            strict=False,
        ):
            padding = " " * (col_width - len(flag_str) + 2)
            if is_required:
                desc_field = f"{desc} (required)"
            elif disp_default:
                desc_field = f'{desc} (default: "{disp_default}")'
            else:
                desc_field = desc
            lines.append(f"{flag_str}{padding}{desc_field}")
        help_padding = " " * (col_width - len(help_flag) + 2)
        lines.append(f"{help_flag}{help_padding}Show this help")
        lines.extend(["EOF", "  return", "}"])
        return "\n".join(lines)

    def _section_arg_parse(self, options: dict) -> str:
        """Emit the if/else/fi CLI-vs-env-var argument parsing block."""
        cli_inits: list[str] = []
        case_arms: list[str] = []
        env_reads: list[str] = []

        for key, opt in options.items():
            vname = _opt_to_var(key)
            typ = opt.get("type", "string")
            flag = _opt_to_flag(key)
            # Arrays are intentionally NOT pre-initialised: bash +=() on an unset
            # variable is safe, and pre-setting to () would fool the declare-based
            # default check.
            if typ != "array":
                if "default" not in opt:
                    cli_inits.append(f'  {vname}=""')
                else:
                    cli_inits.append(f"  {vname}={_shell_val(opt['default'], typ)}")
            if typ == "array":
                case_arms.append(
                    self._render_template(
                        "case_arm_array",
                        FLAG=flag,
                        VAR=vname,
                        KEY=key,
                    ),
                )
                env_reads.append(
                    self._render_template(
                        "env_read_array",
                        VAR=vname,
                        KEY=key,
                    ),
                )
            else:
                case_arms.append(
                    self._render_template(
                        "case_arm_scalar",
                        FLAG=flag,
                        VAR=vname,
                        KEY=key,
                    ),
                )
                env_reads.append(
                    self._render_template(
                        "env_read_scalar",
                        VAR=vname,
                        KEY=key,
                    ),
                )

        lines = [
            'if [ "$#" -gt 0 ]; then',
            '  logging__info "Script called with arguments: $*"',
        ]
        lines.extend(cli_inits)
        lines.extend(['  while [ "$#" -gt 0 ]; do', "    case $1 in"])
        lines.extend(case_arms)
        lines.extend(
            [
                "      -h | --help)",
                "        __usage__",
                "        exit 0",
                "        ;;",
                "      --*)",
                "        logging__error \"Unknown option: '${1}'\"",
                "        exit 1",
                "        ;;",
                "      *)",
                "        logging__error \"Unexpected argument: '${1}'\"",
                "        exit 1",
                "        ;;",
                "    esac",
                "  done",
                "else",
                '  logging__info "Script called with no arguments.'
                ' Read environment variables."',
            ],
        )
        lines.extend(env_reads)
        lines.append("fi")
        lines.append("logging__set_level")
        return "\n".join(lines)

    def _section_defaults(self, options: dict) -> str:
        """Emit the '# Apply defaults.' block."""
        blocks = ["# Apply defaults."]
        for key, opt in options.items():
            vname = _opt_to_var(key)
            typ = opt.get("type", "string")
            if "default" not in opt:
                continue
            if typ == "array":
                raw_default = opt["default"]
                if raw_default == "" or raw_default is None:
                    blocks.append(
                        self._render_template(
                            "default_array_empty",
                            VAR=vname,
                            KEY=key,
                        ),
                    )
                else:
                    # Embed the default as an ANSI-C quoted string so newlines
                    # are preserved.
                    escaped = (
                        str(raw_default)
                        .replace("\\", "\\\\")
                        .replace("'", "\\'")
                        .replace("\n", "\\n")
                        .replace("\r", "\\r")
                    )
                    disp = ", ".join(str(raw_default).splitlines())
                    blocks.append(
                        self._render_template(
                            "default_array_value",
                            VAR=vname,
                            ESCAPED=escaped,
                            KEY=key,
                            DISP=disp,
                        ),
                    )
            else:
                rhs = _shell_val(opt["default"], typ)
                if typ == "boolean":
                    disp = "true" if opt["default"] else "false"
                elif opt["default"] == "" or opt["default"] is None:
                    disp = ""
                else:
                    disp = str(opt["default"])
                blocks.append(
                    self._render_template(
                        "default_scalar",
                        VAR=vname,
                        RHS=rhs,
                        KEY=key,
                        DISP=disp,
                    ),
                )
        return "\n".join(blocks)

    def _section_validation(self, options: dict) -> str:
        """Emit required-argument checks and enum validation.

        Returns '' if neither applies.
        """
        required_opts = [(k, v) for k, v in options.items() if "default" not in v]
        enum_opts = [(k, v) for k, v in options.items() if v.get("enum")]
        if not required_opts and not enum_opts:
            return ""

        parts: list[str] = []
        if required_opts:
            checks: list[str] = []
            for key, opt in required_opts:
                vname = _opt_to_var(key)
                tpl = (
                    "validation_required_array"
                    if opt.get("type", "string") == "array"
                    else "validation_required_scalar"
                )
                checks.append(self._render_template(tpl, VAR=vname, KEY=key))
            parts.append("# Check required arguments.\n" + "\n".join(checks))

        if enum_opts:
            validations: list[str] = []
            for key, opt in enum_opts:
                vname = _opt_to_var(key)
                typ = opt.get("type", "string")
                values = [
                    item["value"] if isinstance(item, dict) else str(item)
                    for item in opt["enum"]
                ]
                expected = ", ".join(repr(v) if v == "" else v for v in values)
                pattern = " | ".join("''" if v == "" else v for v in values)
                tpl = (
                    "validation_enum_array"
                    if typ == "array"
                    else "validation_enum_scalar"
                )
                validations.append(
                    self._render_template(
                        tpl,
                        VAR=vname,
                        KEY=key,
                        PATTERN=pattern,
                        EXPECTED=expected,
                    ),
                )
            parts.append("# Validate enum options.\n" + "\n".join(validations))

        return "\n\n".join(parts)

    def _section_unexport(self, options: dict) -> str:
        """Emit the 'declare +x' unexport line for all scalar option variables."""
        scalar_vars = [
            _opt_to_var(k)
            for k, v in options.items()
            if v.get("type", "string") != "array"
        ]
        if not scalar_vars:
            return ""
        return "\n".join(
            [
                "# Unexport option variables — values remain accessible in this"
                " script but",
                "# are not inherited by child processes.",
                "declare +x " + " ".join(scalar_vars),
            ],
        )

    def _section_prefix_helpers(self, prefix_groups: dict, feature_id: str) -> str:
        """Emit prefix resolver, symlinks, and exports bash functions."""
        if not prefix_groups:
            return ""

        _owner, _repo = git_owner_repo()
        fn_blocks: list[str] = [
            "# ── prefix-group helpers (generated)"
            " ──────────────────────────────────────────────",
        ]
        post_install_blocks: list[str] = []
        resolver_calls: list[str] = []
        # cmd_var → first_bin; needs bare-binary fallback when guarded.
        guarded_cmd_vars: dict[str, str] = {}

        for group_id, group_cfg in prefix_groups.items():
            prefix_cfg: dict = group_cfg.get("prefix", {})
            symlink_cfg: dict = group_cfg.get("symlink", {})
            exports_cfg: dict = group_cfg.get("exports", {})

            option_name: str | None = group_cfg.get("option_name")
            skip_symlink: bool = symlink_cfg.get("skip", False)
            skip_exports: bool = exports_cfg.get("skip", False)
            default_root: str = prefix_cfg.get("root", "/usr/local")
            default_nonroot: str = prefix_cfg.get("nonroot", "${HOME}/.local")
            symlink_root: str = symlink_cfg.get("root", "/usr/local/bin")
            symlink_nonroot: str = symlink_cfg.get("nonroot", "${HOME}/.local/bin")
            bins: list[str] = prefix_cfg.get("bins", [])
            bin_dir: str = prefix_cfg.get("bin_dir", "bin")
            applies_when: list | None = group_cfg.get("applies_when")
            activation_cfg: dict | None = group_cfg.get("activation")

            stem = option_name or (f"{group_id}_prefix" if group_id else "prefix")
            opt_prefix = stem
            opt_symlinks = f"{stem}_symlinks"
            opt_exports = f"{stem}_exports"
            opt_discovery = f"{stem}_discovery"

            var_prefix = _opt_to_var(opt_prefix)
            var_symlinks = _opt_to_var(opt_symlinks)
            var_exports = _opt_to_var(opt_exports)
            var_discovery = _opt_to_var(opt_discovery)

            safe_id = group_id.replace("-", "_")
            if option_name:
                fn_resolve = f"resolve_{option_name}"
            elif group_id:
                fn_resolve = f"resolve_{safe_id}_prefix"
            else:
                fn_resolve = "resolve_prefix"
            fn_activation_snippet = f"{stem}_activation_snippet"
            var_activations = _opt_to_var(f"{stem}_activations")
            activation_marker = f"{stem} activation ({feature_id})"
            activation_profile_d = f"{_owner}-{_repo}-{feature_id}-{stem}-activation.sh"

            optname_disp = option_name or opt_prefix

            # Resolver function
            fn_blocks.append(
                self._render_template(
                    "prefix_resolver",
                    FUNC_NAME=fn_resolve,
                    PREFIX_VAR=var_prefix,
                    OPTNAME=optname_disp,
                    RESOLUTION_BLOCK=_make_resolution_block(
                        var_prefix,
                        default_root,
                        default_nonroot,
                        prefix_cfg.get("platform_overrides", []),
                    ),
                )
            )

            # Activation snippet stub (body overrides to provide content and exit code)
            if activation_cfg:
                fn_blocks.append(
                    f"# shellcheck disable=SC2329,SC2317\n"
                    f"{fn_activation_snippet}() {{ return 1; }}"
                )

            # Discovery params for shell__run_prefix_discovery call.
            first_bin = bins[0] if bins else ""
            bins_str = " ".join(bins) if bins else ""
            marker = (
                f"{first_bin} PATH ({feature_id})"
                if first_bin
                else f"PATH ({feature_id})"
            )
            if group_id:
                cmd_var = f"_DF_EXPECTED_CMD_{group_id.upper().replace('-', '_')}"
            else:
                cmd_var = "_DF_EXPECTED_CMD"

            # Discovery block for _prefix_post_install__generated()
            # Skip entirely when both symlinks and exports are disabled — the call
            # would be a no-op side-effect-wise, and the computed cmd path
            # (prefix/bin/name) would be wrong for installs like nvm that don't
            # place binaries directly under the prefix/bin directory.
            if not (skip_symlink and skip_exports):
                discovery_block = self._build_discovery_block(
                    _DiscoveryParams(
                        stem=stem,
                        var_prefix=var_prefix,
                        bin_dir=bin_dir,
                        var_discovery=var_discovery,
                        var_runtime_path=_opt_to_var("runtime_path"),
                        bins_str=bins_str,
                        var_symlinks=var_symlinks,
                        var_exports=var_exports,
                        marker=marker,
                        first_bin=first_bin,
                        cmd_var=cmd_var,
                        skip_symlink=skip_symlink,
                        skip_exports=skip_exports,
                        symlink_root=symlink_root,
                        symlink_nonroot=symlink_nonroot,
                    )
                )
                post_install_blocks.append(
                    _wrap_applies_when(applies_when, discovery_block)
                )
                if applies_when and first_bin and cmd_var not in guarded_cmd_vars:
                    guarded_cmd_vars[cmd_var] = first_bin

            # Activation block for _prefix_post_install__generated()
            if activation_cfg:
                activation_block = self._render_template(
                    "prefix_activation",
                    STEM=stem,
                    MARKER=activation_marker,
                    PROFILE_D_NAME=activation_profile_d,
                    SNIPPET_FUNC=fn_activation_snippet,
                    ACTIVATIONS_VAR=var_activations,
                    PREFIX_VAR=var_prefix,
                )
                post_install_blocks.append(
                    _wrap_applies_when(applies_when, activation_block)
                )

            # Write-group block for _prefix_post_install__generated()
            write_group_cfg: dict | None = group_cfg.get("write_group")
            if write_group_cfg is not None:
                if group_id:
                    wg_key = f"{group_id}_write_group"
                    wu_key = f"{group_id}_write_users"
                else:
                    wg_key = "write_group"
                    wu_key = "write_users"
                wg_var = _opt_to_var(wg_key)
                wu_var = _opt_to_var(wu_key)
                owner_var_name: str = write_group_cfg.get("owner_var", "")
                if owner_var_name:
                    owner_expr = f'"${{{owner_var_name}}}"'
                else:
                    owner_expr = '"$(id -nu)"'
                _set_perms = (
                    f"  users__set_write_permissions"
                    f' "${{{var_prefix}}}"'
                    f" {owner_expr}"
                    f' "${{{wg_var}}}"'
                    f' "${{_write_users[@]}}"'
                )
                write_group_block = (
                    f"_wargs=()\n"
                    f'if [[ "${{#{wu_var}[@]}}" -gt 0 ]]; then\n'
                    f"  _wargs=(--current false"
                    f" --remote false --container false)\n"
                    f'  for _u in "${{{wu_var}[@]}}"'
                    f'; do _wargs+=(--user "$_u"); done\n'
                    f"fi\n"
                    f"mapfile -t _write_users"
                    f' < <(users__resolve_list "${{_wargs[@]}}")\n'
                    f'if [[ -n "${{{wg_var}:-}}" ]]; then\n'
                    f"{_set_perms}\n"
                    f"fi"
                )
                post_install_blocks.append(
                    _wrap_applies_when(applies_when, write_group_block)
                )

            resolver_calls.append(fn_resolve)

        # Bare-binary fallbacks ensure cmd-vars are always set even when an
        # applies_when guard prevented the discovery block from running (inactive
        # install method, or a non-prefix method with no prefix_group at all).
        # The := operator makes each line a no-op when discovery already set the var.
        for _cv, _fb in guarded_cmd_vars.items():
            post_install_blocks.append(f': "${{{_cv}:={_fb}}}"')

        # _prefix_post_install__generated() aggregating all per-group discovery blocks
        post_install_body = "\n\n".join(post_install_blocks)
        fn_blocks.append(
            "# shellcheck disable=SC2329,SC2317\n"
            "_prefix_post_install__generated() {\n"
            f"{post_install_body}\n"
            "return\n"
            "}"
        )

        # _prefix_post_install() shadows the preamble no-op stub
        fn_blocks.append(
            "_prefix_post_install() {\n  _prefix_post_install__generated\n  return\n}"
        )

        # Inline resolver calls (run after defaults are applied)
        return "\n\n".join(fn_blocks) + "\n\n" + "\n".join(resolver_calls)

    def _section_dep_helpers(self, run_deps: dict, build_deps: dict) -> str:
        """Emit _<group>_deps__install() / _<group>_deps__cleanup() helper functions."""
        if not run_deps and not build_deps:
            return ""
        blocks = [
            "# ── dep-group helpers (generated)"
            " ──────────────────────────────────────────────",
        ]
        blocks.extend(
            self._render_template(
                "dep_helper_run",
                SAFE=gn.replace("-", "_"),
                GROUP=gn,
            )
            for gn in run_deps
        )
        blocks.extend(
            self._render_template(
                "dep_helper_build",
                SAFE=gn.replace("-", "_"),
                GROUP=gn,
            )
            for gn in build_deps
        )
        return "\n".join(blocks)

    def _section_base_deps_call(self, run_deps: dict, build_deps: dict) -> str:
        """Emit root-guarded _base_deps__install() calls: build first, then run."""
        parts = []
        if "base" in build_deps:
            parts.append(self._render_template("build_base_deps_call"))
        if "base" in run_deps:
            parts.append(self._render_template("base_deps_call"))
        return "\n\n".join(parts)

    def _shfmt_format(self, text: str) -> str:
        """Format a bash script fragment through shfmt, respecting .editorconfig.

        Writes to a temp file in the repo root so shfmt finds the .editorconfig
        style settings.  Returns *text* unchanged if shfmt is not on PATH.
        """
        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".sh",
            dir=self._repo_dirpath,
            delete=False,
            encoding="utf-8",
        ) as tmp:
            tmp.write(text)
            tmp_path = Path(tmp.name)
        try:
            result = subprocess.run(
                ["shfmt", "-w", str(tmp_path)],
                capture_output=True,
                check=False,
                cwd=self._repo_dirpath,
            )
            if result.returncode == 0:
                return tmp_path.read_text(encoding="utf-8")
            return text
        except FileNotFoundError:
            return text
        finally:
            tmp_path.unlink(missing_ok=True)

    def _render_template(self, name: str, **subs: str) -> str:
        """Load a shell snippet template and substitute @@KEY@@ placeholders."""
        template = self._templates[name]
        for key, val in subs.items():
            template = template.replace(f"@@{key}@@", val)
        return template

    @staticmethod
    def _build_discovery_block(p: _DiscoveryParams) -> str:
        if p.skip_symlink and p.skip_exports:
            comment_suffix = " (symlinks and exports disabled)"
        elif p.skip_symlink:
            comment_suffix = " (no symlinks)"
        else:
            comment_suffix = ""
        args: list[str] = [
            f'--prefix "${{{p.var_prefix}}}"',
            f'--bin-dir "{p.bin_dir}"',
            f'--discovery "${{{p.var_discovery}:-auto}}"',
            f'--runtime-path "${{{p.var_runtime_path}:-${{PATH:-}}}}"',
        ]
        if not p.skip_symlink:
            args += [f'--bins "{p.bins_str}"', f'--symlinks-ref "{p.var_symlinks}"']
            if p.symlink_root != "/usr/local/bin":
                args.append(f'--symlink-root "{p.symlink_root}"')
            if p.symlink_nonroot != "${HOME}/.local/bin":
                args.append(f'--symlink-nonroot "{p.symlink_nonroot}"')
        if not p.skip_exports:
            args += [
                f'--exports-ref "{p.var_exports}"',
                f'--marker "{p.marker}"',
                '--profile-d "${_EXPORT_PROFILE_D}"',
            ]
        args += [f'--bin "{p.first_bin}"', f'--cmd-var "{p.cmd_var}"']
        if p.skip_symlink:
            args.append("--no-symlinks")
        if p.skip_exports:
            args.append("--no-exports")
        fn_name = f"{p.stem}_discovery"
        lines = [
            f"# -- discovery: {p.stem}{comment_suffix} --",
            f'logging__fn_entry "{fn_name}"',
            "shell__run_prefix_discovery \\",
        ]
        for i, arg in enumerate(args):
            lines.append(f"  {arg} \\" if i < len(args) - 1 else f"  {arg}")
        lines.append(f'logging__fn_exit "{fn_name}"')
        return "\n".join(lines)

    @staticmethod
    def _load_templates(templates_dirpath: Path) -> dict[str, str]:
        templates = {}
        for template_path in templates_dirpath.glob("*.tmpl"):
            template_name = template_path.name.removesuffix(".sh.tmpl")
            templates[template_name] = template_path.read_text(encoding="utf-8").rstrip(
                "\n",
            )
        return templates


# ── Pure utilities ────────────────────────────────────────────────────────────


def _make_resolution_block(
    var_prefix: str,
    default_root: str,
    default_nonroot: str,
    platform_overrides: list[dict],
) -> str:
    """Build the shell if/elif/else resolution block for a prefix resolver.

    Without platform_overrides, emits a simple uid-based if/else.
    With overrides, prepends `os__match_spec` branches before the uid fallback.
    Each override dict must have ``when`` (mapping of key→value) and ``default``.
    ``default_root`` / ``default_nonroot`` within an override override ``default``
    per uid, mirroring the top-level default_root / default_nonroot semantics.
    """
    indent = "      "  # 6 spaces — inside case "")
    lines: list[str] = []
    first = True
    for override in platform_overrides:
        when: dict = override.get("when", {})
        default: str = override["default"]
        root_val: str = override.get("root", default)
        nonroot_val: str = override.get("nonroot", default)
        when_args = " ".join(f"{k}={v}" for k, v in when.items())
        keyword = "if" if first else "elif"
        lines.append(f"{indent}{keyword} os__match_spec {when_args}; then")
        if root_val == nonroot_val:
            lines.append(f'{indent}  {var_prefix}="{root_val}"')
        else:
            lines.append(f'{indent}  if [ "$(id -u)" = "0" ]; then')
            lines.append(f'{indent}    {var_prefix}="{root_val}"')
            lines.append(f"{indent}  else")
            lines.append(f'{indent}    {var_prefix}="{nonroot_val}"')
            lines.append(f"{indent}  fi")
        first = False
    uid_keyword = "elif" if platform_overrides else "if"
    lines.append(f'{indent}{uid_keyword} [ "$(id -u)" = "0" ]; then')
    lines.append(f'{indent}  {var_prefix}="{default_root}"')
    lines.append(f"{indent}else")
    lines.append(f'{indent}  {var_prefix}="{default_nonroot}"')
    lines.append(f"{indent}fi")
    return "\n".join(lines)


def _first_sentence(text: str) -> str:
    """Return the first non-empty line of a description."""
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped:
            return stripped
    return text.strip()


def _wrap_applies_when(applies_when: list | None, block: str) -> str:
    """Wrap a shell block in a positive if/case guard from an applies_when condition.

    Returns the block unchanged when applies_when is absent or unparseable.
    Input format: [{varname: [val1, val2, ...]}]
    """
    if not applies_when:
        return block
    entry = applies_when[0]
    if not isinstance(entry, dict) or len(entry) != 1:
        return block
    var_name, values = next(iter(entry.items()))
    var = _opt_to_var(var_name)
    if not values:
        return block
    if len(values) == 1:
        return f'if [ "${{{var}}}" = "{values[0]}" ]; then\n{block}\nfi'
    pattern = " | ".join(str(v) for v in values)
    return f'case "${{{var}}}" in {pattern})\n{block}\n;;\nesac'


def _opt_to_var(key: str) -> str:
    """Convert a schema-validated option key to its installer env-var name.

    Option keys are constrained by features/metadata.schema.json to start with an
    ASCII letter and then contain only ASCII letters, digits, underscores, or
    hyphens. Given that contract, env-var generation is just uppercase plus
    '-' -> '_'.
    """
    return key.upper().replace("-", "_")


def _opt_to_flag(key: str) -> str:
    """Convert an option key to its --flag form."""
    return f"--{key}"


def _shell_val(default: object, typ: str) -> str:
    """Format a YAML default value as a shell assignment RHS (non-array types only)."""
    if typ == "boolean":
        return "true" if default else "false"
    if default == "" or default is None:
        return '""'
    return f'"{default}"'


def _usage_type_hint(opt: dict) -> str:
    """Return a concise type hint for the --help usage line."""
    typ = opt["type"]
    enum_raw = opt.get("enum", [])
    enum_values = [
        item["value"] if isinstance(item, dict) else str(item) for item in enum_raw
    ]
    if typ == "boolean":
        return "{true,false}"
    if typ == "array":
        if enum_values:
            return "{" + "|".join(enum_values) + "}  (repeatable)"
        return "<value>  (repeatable)"
    if enum_values:
        return "{" + "|".join(enum_values) + "}"
    return "<value>"
