"""sync-src.py — Assembles each feature's src/ directory from features/ + lib/ + features/bootstrap.sh:

  - features/*/metadata.yaml → src/*/devcontainer-feature.json
  - features/*/metadata.yaml → src/*/dependencies/*.yaml
  - features/*/install.bash  → src/*/install.bash (autogenerated header prepended)
  - lib/                     → src/*/_lib/
  - features/bootstrap.sh    → src/*/install.sh
  - features/*/files/        → src/*/files/ (copied, not symlinked)

Usage:
  python3 scripts/sync-src.py           # sync all features
  python3 scripts/sync-src.py --check   # verify src/ is up to date (exits non-zero if stale)
"""

from __future__ import annotations

import fnmatch
import json
import re
import sys
from pathlib import Path
import subprocess
import tempfile
from typing import Literal

import jsonschema
import yaml


from proman.git_utils import git_owner_repo, git_repo_root


REPO_DIRPATH = git_repo_root()
REPO_OWNER, REPO_NAME = git_owner_repo()

# Constants
LIB_DIRPATH = REPO_DIRPATH / "lib"
FEATURES_DIRPATH = REPO_DIRPATH / "features"
SRC_DIRPATH = REPO_DIRPATH / "src"
INSTALL_SCRIPT_TEMPLATES_DIRPATH = FEATURES_DIRPATH / "_install.sh-templates"
COMMON_OPTIONS_FILEPATH = FEATURES_DIRPATH / "shared-options.yaml"
METADATA_SCHEMA_FILEPATH = FEATURES_DIRPATH / "metadata.schema.json"
OSPKG_MANIFEST_SCHEMA_FILEPATH = LIB_DIRPATH / "ospkg.manifest.schema.json"
BOOTSTRAP_FILEPATH = FEATURES_DIRPATH / "bootstrap.sh"
LICENSE_URL = f"https://github.com/{REPO_OWNER}/{REPO_NAME}/blob/main/LICENSE"
DOC_URL_TEMPLATE = f"https://{REPO_OWNER}.github.io/{REPO_NAME}/features/{{feature_id}}"
OSPKG_MANIFEST_SCHEMA_ID = f"https://raw.githubusercontent.com/{REPO_OWNER}/{REPO_NAME}/main/{OSPKG_MANIFEST_SCHEMA_FILEPATH.relative_to(REPO_DIRPATH)}"
INSTALL_SCRIPT_HEADER_END_MARKER = "# END OF AUTOGENERATED BLOCK"


def run(check_only: bool = False):

    n_features: int = 0
    n_failures: dict[str, int] = {
        "read": 0,
        "augmentation": 0,
        "schema validation": 0,
        "sync": 0,
    }

    lib_files = gather_lib_files()
    bootstrap_file = gather_bootstrap()

    for feature_dirpath in sorted(FEATURES_DIRPATH.iterdir()):

        if not feature_dirpath.is_dir() or feature_dirpath.name[0] in (".", "_"):
            continue

        feature_id = feature_dirpath.name
        metadata = read_metadata(feature_id)

        if metadata == 0:
            # No metadata.yaml found; skip without counting as a failure (allows draft features to be added).
            continue

        if metadata == 1:
            n_failures["read"] += 1
            continue

        n_features += 1
        output_files: dict[Path, str] = {}

        augmentation_ok = augment_metadata(feature_id, metadata)
        if not augmentation_ok:
            n_failures["augmentation"] += 1
            continue

        validation_ok = validate_metadata_schema(feature_id, metadata)
        if not validation_ok:
            n_failures["schema validation"] += 1
            continue

        metadata["id"] = feature_id
        dependency_manifests = generate_dependency_manifests(metadata)
        output_files.update(dependency_manifests)

        sanitize_markdown(metadata)

        metadata_json = generate_metadata_json(feature_id, metadata)
        output_files.update(metadata_json)

        install_script = generate_install_script(feature_id, metadata)
        output_files.update(install_script)
        output_files.update(lib_files)
        output_files.update(bootstrap_file)
        output_files.update(gather_feature_files(feature_id))

        sync_ok = sync_source_files(feature_id, output_files, check_only=check_only)
        if not sync_ok:
            n_failures["sync"] += 1

    log("\nFinal results:")
    if any(n_failures.values()):
        n_failures_total = sum(n_failures.values())
        log(f"\n{n_failures_total}/{n_features} feature(s) failed validation.")
        for stage, count in n_failures.items():
            if count:
                log(f"- {count} failed at {stage} stage")
        return 1

    log(f"✅ All {n_features} features passed.")
    return 0






# Dependency Manifest Generation
# ------------------------------

def generate_dependency_manifests(metadata: dict) -> dict[Path, str]:
    """Sync the dependencies/ directory for the given feature based on its metadata."""
    deps = metadata.get("_dependencies")
    if not deps:
        return {}

    dirpath = Path("dependencies")
    manifests = {}

    for lifecycle, groups in deps.items():
        for dep_name, dep_content in groups.items():
            dep_path = dirpath / lifecycle / f"{dep_name}.yaml"
            manifest = yaml.dump(dep_content, default_flow_style=False, sort_keys=False, allow_unicode=True)
            manifests[dep_path] = manifest
    return manifests


# Metadata JSON Generation
# ------------------------

def generate_metadata_json(feature_id: str, metadata: dict) -> dict[Path, str]:
    """Generate devcontainer-feature.json content from parsed YAML data.

    Returns the JSON string (with trailing newline).
    """
    metadata_json_dict: dict = {
        "documentationURL": DOC_URL_TEMPLATE.format(feature_id=feature_id),
        "licenseURL": LICENSE_URL
    }

    for key, value in metadata.items():
        if key.startswith("_"):
            continue
        if key != "options":
            metadata_json_dict[key] = value
            continue

        options = {}
        for option_id, option_raw in value.items():
            option = {}
            for k, v in option_raw.items():
                if k.startswith("_"):
                    continue
                if k == "type" and v == "array":
                    option[k] = "string"
                elif k in ("enum", "proposals"):
                    option[k] = [item["value"] for item in v]
                else:
                    option[k] = v
            options[option_id] = option
        metadata_json_dict[key] = options

    metadata_json = json.dumps(metadata_json_dict, sort_keys=True, indent=3, ensure_ascii=False) + "\n"
    return {Path("devcontainer-feature.json"): metadata_json}




# File Gathering (lib, bootstrap, feature files/)
# ------------------------------------------------

def gather_lib_files() -> dict[Path, str]:
    """Read all files from lib/ and return them keyed by their _lib/-relative output paths."""
    files: dict[Path, str] = {}
    for src_path in sorted(LIB_DIRPATH.rglob("*")):
        if not src_path.is_file():
            continue
        rel = src_path.relative_to(LIB_DIRPATH)
        files[Path("_lib") / rel] = src_path.read_text(encoding="utf-8")
    return files


def _gitignore_basename_patterns() -> list[str]:
    """Return the basename-only patterns from the repo .gitignore.

    Basename-only patterns are those without a '/' in their body — they match
    any file regardless of directory depth, exactly as git does.  Path-anchored
    patterns (e.g. ``/src/``, ``docs/features/``) are intentionally excluded so
    that this function returns only file-name patterns (e.g. ``.DS_Store``,
    ``._*``, ``Thumbs.db``).
    """
    gitignore = REPO_DIRPATH / ".gitignore"
    if not gitignore.is_file():
        return []
    patterns: list[str] = []
    for raw in gitignore.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("!"):
            continue
        # Directory-only patterns (trailing '/') are not file patterns.
        if line.endswith("/"):
            continue
        # Strip leading '/' anchors before the slash check.
        body = line.lstrip("/")
        # Skip patterns that contain a '/' — they are path-specific, not
        # basename patterns.
        if "/" in body:
            continue
        patterns.append(body)
    return patterns


_GITIGNORE_BASENAME_PATTERNS: list[str] = _gitignore_basename_patterns()


def _is_junk_file(name: str) -> bool:
    """Return True if the filename matches any basename-only .gitignore pattern.

    Developers control which files are considered junk by editing .gitignore;
    no patterns are hardcoded here.
    """
    return any(fnmatch.fnmatch(name, p) for p in _GITIGNORE_BASENAME_PATTERNS)


def gather_bootstrap() -> dict[Path, str]:
    """Read features/bootstrap.sh and return it keyed as install.sh."""
    return {Path("install.sh"): BOOTSTRAP_FILEPATH.read_text(encoding="utf-8")}


def gather_feature_files(feature_id: str) -> dict[Path, str]:
    """Read features/<id>/files/** and return them keyed by their files/-relative output paths.

    Only git-tracked files are included.  This ensures that OS-generated
    artefacts (e.g. ``.DS_Store``) that happen to exist on disk but were never
    committed are silently ignored without any hardcoded filename list.
    """
    files_dir = FEATURES_DIRPATH / feature_id / "files"
    if not files_dir.is_dir():
        return {}
    ls = subprocess.run(
        ["git", "ls-files", "-z", "--", "."],
        capture_output=True, text=True, check=True,
        cwd=files_dir,
    )
    tracked = frozenset(
        files_dir / rel for rel in ls.stdout.split("\0") if rel
    )
    return {
        Path("files") / src_path.relative_to(files_dir): src_path.read_text(encoding="utf-8")
        for src_path in sorted(files_dir.rglob("*"))
        if src_path.is_file() and src_path in tracked
    }


# File Sync
# ---------

def sync_source_files(feature_id: str, new_files: dict[Path, str], check_only: bool = False) -> bool:

    feature_src_dir = SRC_DIRPATH / feature_id
    old_files = {
        path.relative_to(feature_src_dir): path.read_text(encoding="utf-8")
        for path in sorted(feature_src_dir.rglob("*"))
        if path.is_file() and not _is_junk_file(path.name)
    } if feature_src_dir.exists() else {}

    is_in_sync = True

    for new_filepath, new_content in new_files.items():

        if new_filepath not in old_files:
            if check_only:
                is_in_sync = False
                log(f"⛔ {feature_id}: {new_filepath} is missing")
            else:
                (feature_src_dir / new_filepath).parent.mkdir(parents=True, exist_ok=True)
                (feature_src_dir / new_filepath).write_text(new_content, encoding="utf-8")
                log(f"✅ {feature_id}: {new_filepath} created")
            continue

        if old_files[new_filepath] == new_content:
            log(f"✅ {feature_id}: {new_filepath} unchanged")
            continue

        if check_only:
            is_in_sync = False
            log(f"⛔ {feature_id}: {new_filepath} is stale")
        else:
            (feature_src_dir / new_filepath).write_text(new_content, encoding="utf-8")
            log(f"✅ {feature_id}: {new_filepath} updated")

    # Check/remove stale files that are no longer declared in metadata.
    for old_filepath in old_files:
        if old_filepath not in new_files:
            if check_only:
                is_in_sync = False
                log(f"⛔ {feature_id}: {old_filepath} must be removed")
            else:
                (feature_src_dir / old_filepath).unlink()
                log(f"🗑️  {feature_id}: {old_filepath} removed")
    return is_in_sync


# Logging
# -------

def log(msg: str) -> None:
    print(msg, file=sys.stderr)


if __name__ == "__main__":
    check_only = "--check" in sys.argv
    sys.exit(run(check_only=check_only))
