# shellcheck shell=bash
# Argument parsing helpers for feature install scripts.
#
# Provides validation and default-setting functions that replace inline bash
# blocks generated by install_script.py.  All functions use indirect variable
# references (${!VAR} / nameref) so callers pass the variable *name*, not its
# value.

_argparse__label() {
  # User-facing option label: bash vars are UPPER_SNAKE; metadata/CLI use lower_snake.
  printf '%s' "${1,,}"
}

argparse__var_declared() {
  # @brief argparse__var_declared VAR — Return 0 if VAR is declared in this shell (including empty arrays).
  #
  # Prefer over [[ -v VAR ]] when testing install-option arrays: bash treats empty
  # arrays (e.g. PREFIX=()) as unset for -v but as declared for declare -p.
  # Use [[ -v VAR ]] when inherited environment bindings must be detected
  # (__dep_manifest_var_set__).
  declare -p "$1" &> /dev/null
}

argparse__validate_bool() {
  # @brief argparse__validate_bool VAR — Exits 1 if $VAR is not "true" or "false".
  local _label
  _label="$(_argparse__label "$1")"
  case "${!1}" in
    true | false) ;;
    *)
      logging__error "Invalid value for '${_label}': '${!1}' (expected: true, false)"
      exit 1
      ;;
  esac
}

argparse__validate_enum() {
  # @brief argparse__validate_enum VAR [valid...] — Exits 1 if $VAR is not among the valid values.
  local _var="$1" _label
  _label="$(_argparse__label "$_var")"
  shift
  local _val="${!_var}" _v
  for _v in "$@"; do
    [[ "$_val" == "$_v" ]] && return 0
  done
  local _expected="" _ev
  for _ev in "$@"; do
    [[ -z "$_ev" ]] && _expected+="'', " || _expected+="${_ev}, "
  done
  logging__error "Invalid value for '${_label}': '${_val}' (expected: ${_expected%, })"
  exit 1
}

argparse__validate_enum_array() {
  # @brief argparse__validate_enum_array VAR [valid...] — Exits 1 if any element of array $VAR is not among the valid values.
  local _var="$1" _label
  _label="$(_argparse__label "$_var")"
  shift
  local -n _ave_ref="$_var"
  local _val _v _matched
  for _val in "${_ave_ref[@]}"; do
    _matched=false
    for _v in "$@"; do
      [[ "$_val" == "$_v" ]] && {
        _matched=true
        break
      }
    done
    if [[ "$_matched" != true ]]; then
      local _expected="" _ev
      for _ev in "$@"; do
        [[ -z "$_ev" ]] && _expected+="'', " || _expected+="${_ev}, "
      done
      logging__error "Invalid value for '${_label}': '${_val}' (expected: ${_expected%, })"
      exit 1
    fi
  done
}

argparse__validate_integer() {
  # @brief argparse__validate_integer VAR — Exits 1 if $VAR is not a valid integer.
  local _label
  _label="$(_argparse__label "$1")"
  if [[ ! "${!1}" =~ ^-?[0-9]+$ ]]; then
    logging__error "Invalid value for '${_label}': '${!1}' is not a valid integer."
    exit 1
  fi
}

argparse__validate_integer_min() {
  # @brief argparse__validate_integer_min VAR MIN — Exits 1 if $VAR < MIN.
  local _label
  _label="$(_argparse__label "$1")"
  if ((${!1} < ${2})); then
    logging__error "Invalid value for '${_label}': '${!1}' must be >= ${2}."
    exit 1
  fi
}

argparse__validate_integer_max() {
  # @brief argparse__validate_integer_max VAR MAX — Exits 1 if $VAR > MAX.
  local _label
  _label="$(_argparse__label "$1")"
  if ((${!1} > ${2})); then
    logging__error "Invalid value for '${_label}': '${!1}' must be <= ${2}."
    exit 1
  fi
}

_argparse__validate_path_value() {
  # @brief _argparse__validate_path_value VAR VALUE OP — Test one path string; VAR is for error labels only.
  local _var="$1" _val="$2" _op="$3" _label
  _label="$(_argparse__label "$_var")"
  [[ -z "$_val" ]] && return 0
  local _ok=false
  case "$_op" in
    -d) [[ -d "$_val" ]] && _ok=true ;;
    -f) [[ -f "$_val" ]] && _ok=true ;;
    -e) [[ -e "$_val" ]] && _ok=true ;;
    -x) [[ -x "$_val" ]] && _ok=true ;;
    -r) [[ -r "$_val" ]] && _ok=true ;;
    -s) [[ -s "$_val" ]] && _ok=true ;;
    -w) [[ -w "$_val" ]] && _ok=true ;;
    "! -"[dferswx])
      ! test "${_op#! }" "$_val" && _ok=true
      ;;
    *)
      logging__error "unsupported path test '${_op}'."
      exit 1
      ;;
  esac
  if [[ "$_ok" != true ]]; then
    logging__error "Invalid value for '${_label}': '${_val}' failed path test '${_op}'."
    exit 1
  fi
}

argparse__validate_path() {
  # @brief argparse__validate_path VAR OP — Exits 1 if the path in $VAR fails test OP.
  #
  # OP is a bash unary test operator (e.g. -d, -f, -e).
  # Validation fails when the test does NOT hold.  An empty value is skipped.
  local _val="${!1}"
  _argparse__validate_path_value "$1" "$_val" "$2"
}

argparse__validate_path_array() {
  # @brief argparse__validate_path_array VAR OP [OP...] — Exits 1 if any array element fails test OP.
  #
  # Empty elements are skipped.
  local _var="$1"
  shift
  local -n _arr="$_var"
  local _elem _op
  for _op in "$@"; do
    for _elem in "${_arr[@]}"; do
      [[ -z "$_elem" ]] && continue
      _argparse__validate_path_value "$_var" "$_elem" "$_op"
    done
  done
}

argparse__default() {
  # @brief argparse__default VAR DEFAULT — Sets $VAR to DEFAULT if not already set.
  [ "${!1+defined}" ] && return 0
  local -n _d_ref="$1"
  _d_ref="$2"
  logging__info "Argument '${1}' set to default value \"${2}\"."
}

argparse__default_array() {
  # @brief argparse__default_array VAR — Sets array $VAR to () if not already declared.
  argparse__var_declared "$1" && return 0
  local -n _da_ref="$1"
  _da_ref=()
  logging__info "Argument '${1}' set to default value '(empty)'."
}

argparse__split_lines() {
  # @brief argparse__split_lines VAR TEXT — Split newline-delimited TEXT into array VAR; trim; drop blanks.
  mapfile -t "$1" < <(
    printf '%s\n' "$2" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | grep -v '^$'
  )
}

argparse__normalize_array() {
  # @brief argparse__normalize_array VAR — Trim elements; drop empty/whitespace-only entries (in place).
  local _var="$1" _elem _stripped
  local -n _arr="$_var"
  local _out=()
  for _elem in "${_arr[@]}"; do
    _stripped="${_elem#"${_elem%%[![:space:]]*}"}"
    _stripped="${_stripped%"${_stripped##*[![:space:]]}"}"
    [[ -n "$_stripped" ]] && _out+=("$_stripped")
  done
  _arr=("${_out[@]}")
}

argparse__default_array_value() {
  # @brief argparse__default_array_value VAR VALUE — Sets array $VAR from multi-line VALUE if not already declared.
  #
  # VALUE is the (already shell-expanded) multi-line string; use $'...' at the call site
  # to let bash interpret escape sequences before passing to this function.
  argparse__var_declared "$1" && return 0
  local -n _dav_ref="$1"
  argparse__split_lines _dav_ref "$2"
  local _disp="${2//$'\n'/, }"
  logging__info "Argument '${1}' set to default value \"${_disp}\"."
}

argparse__resolve_uri_options() {
  # @brief argparse__resolve_uri_options <spec>
  #
  # Resolve a newline-delimited URI spec list, rewriting option variables in place.
  #
  # Each non-empty spec line is TAB-delimited:
  #   <key> <TAB> <VAR> <TAB> <type:string|array> <TAB> <chmod_mode_or_empty>
  #
  # Resolution order:
  #   - Build fetch args from shared `FETCH_HEADERS` and `FETCH_NETRC`.
  #   - Choose a materialization root:
  #       - `INSTALLER_DIR` when defined and non-empty,
  #       - else `file__mktmpdir "${_FEAT_ID}-uri"`.
  #   - For each spec:
  #       - `array`: resolve elements via `uri__resolve_list` into `${matdir}/uri/<key>/`.
  #       - `string` with chmod: resolve via `uri__resolve` into a stable dest under `${matdir}/uri/<key>/`.
  #       - `string` without chmod: resolve via `uri__resolve_line` into `${matdir}/uri/<key>/` (remote only).
  #
  # Notes:
  #   - This function requires `lib/uri.sh` to be loaded.
  #   - It is safe under `set -u`: does not reference INSTALLER_DIR unless defined.
  #
  # Returns: 0 on success, non-zero on any failure.
  local _spec="${1:-}"
  [[ -n "${_spec//[[:space:]]/}" ]] || return 0

  argparse__var_declared FETCH_HEADERS || FETCH_HEADERS=()
  [ "${FETCH_NETRC+defined}" ] || FETCH_NETRC=""

  local -a _fetch_args=()
  local _h
  if [[ ${#FETCH_HEADERS[@]} -gt 0 ]]; then
    for _h in "${FETCH_HEADERS[@]}"; do
      [[ -n "${_h}" ]] && _fetch_args+=(--header "${_h}")
    done
  fi
  [[ -n "${FETCH_NETRC:-}" ]] && _fetch_args+=(--netrc-file "${FETCH_NETRC}")

  local _matdir
  if [[ "${INSTALLER_DIR+defined}" == "defined" && -n "${INSTALLER_DIR:-}" ]]; then
    _matdir="${INSTALLER_DIR}"
  else
    _matdir="$(file__mktmpdir "${_FEAT_ID}-uri")"
  fi

  local _line _key _var _typ _chmod _mdir _list _dest
  while IFS= read -r _line || [[ -n "${_line}" ]]; do
    [[ -z "${_line//[[:space:]]/}" ]] && continue
    IFS=$'\t' read -r _key _var _typ _chmod <<< "${_line}"
    [[ -n "${_key:-}" && -n "${_var:-}" && -n "${_typ:-}" ]] || {
      logging__error "invalid spec line: '${_line}'"
      return 1
    }
    _mdir="${_matdir}/uri/${_key}"
    case "${_typ}" in
      array)
        local -n _uri_arr_ref="$_var"
        [[ ${#_uri_arr_ref[@]} -gt 0 ]] || continue
        _list="$(printf '%s\n' "${_uri_arr_ref[@]}")"
        mapfile -t _uri_arr_ref < <(uri__resolve_list "$_list" "$_mdir" "${_fetch_args[@]}" ${_chmod:+--chmod "$_chmod"}) ||
          {
            logging__error "failed to resolve URI array '${_key}'."
            return 1
          }
        ;;
      string)
        local _val="${!_var:-}"
        [[ -n "${_val}" ]] || continue
        mkdir -p "$_mdir"
        if [[ -n "${_chmod:-}" ]]; then
          _dest="$(uri__dest_for_uri "$_mdir" "$_val")"
          local _rc=$?
          [[ $_rc == 0 ]] || {
            logging__error "failed to derive dest for URI '${_key}'."
            return "$_rc"
          }
          uri__resolve "$_val" "$_dest" "${_fetch_args[@]}" --chmod "$_chmod" > /dev/null
          local _rc=$?
          [[ $_rc == 0 ]] || {
            logging__error "failed to resolve URI '${_key}' to '${_dest}'."
            return "$_rc"
          }
          printf -v "$_var" '%s' "$_dest"
        else
          local _resolved_line
          _resolved_line="$(uri__resolve_line "$_val" "$_mdir" "${_fetch_args[@]}")"
          local _rc=$?
          [[ $_rc == 0 ]] || {
            logging__error "failed to resolve URI line '${_key}'."
            return "$_rc"
          }
          printf -v "$_var" '%s' "$_resolved_line"
        fi
        ;;
      *)
        logging__error "unknown type '${_typ}' in spec for '${_key}'."
        return 1
        ;;
    esac
  done <<< "$(printf '%s\n' "$_spec")"

  return 0
}
