# shellcheck shell=bash
# Argument parsing helpers for feature install scripts.
#
# Provides validation and default-setting functions that replace inline bash
# blocks generated by install_script.py.  All functions use indirect variable
# references (${!VAR} / nameref) so callers pass the variable *name*, not its
# value.

# @brief argparse__validate_bool VAR — Exits 1 if $VAR is not "true" or "false".
argparse__validate_bool() {
  case "${!1}" in
    true | false) ;;
    *)
      logging__error "Invalid value for '${1}': '${!1}' (expected: true, false)"
      exit 1
      ;;
  esac
}

# @brief argparse__validate_enum VAR [valid...] — Exits 1 if $VAR is not among the valid values.
argparse__validate_enum() {
  local _var="$1"
  shift
  local _val="${!_var}" _v
  for _v in "$@"; do
    [[ "$_val" == "$_v" ]] && return 0
  done
  local _expected="" _ev
  for _ev in "$@"; do
    [[ -z "$_ev" ]] && _expected+="'', " || _expected+="${_ev}, "
  done
  logging__error "Invalid value for '${_var}': '${_val}' (expected: ${_expected%, })"
  exit 1
}

# @brief argparse__validate_enum_array VAR [valid...] — Exits 1 if any element of array $VAR is not among the valid values.
argparse__validate_enum_array() {
  local _var="$1"
  shift
  local -n _ave_ref="$_var"
  local _val _v _matched
  for _val in "${_ave_ref[@]}"; do
    _matched=false
    for _v in "$@"; do
      [[ "$_val" == "$_v" ]] && { _matched=true; break; }
    done
    if [[ "$_matched" != true ]]; then
      local _expected="" _ev
      for _ev in "$@"; do
        [[ -z "$_ev" ]] && _expected+="'', " || _expected+="${_ev}, "
      done
      logging__error "Invalid value for '${_var}': '${_val}' (expected: ${_expected%, })"
      exit 1
    fi
  done
}

# @brief argparse__validate_integer VAR — Exits 1 if $VAR is not a valid integer.
argparse__validate_integer() {
  if [[ ! "${!1}" =~ ^-?[0-9]+$ ]]; then
    logging__error "Invalid value for '${1}': '${!1}' is not a valid integer."
    exit 1
  fi
}

# @brief argparse__validate_integer_min VAR MIN — Exits 1 if $VAR < MIN.
argparse__validate_integer_min() {
  if (( ${!1} < ${2} )); then
    logging__error "Invalid value for '${1}': '${!1}' must be >= ${2}."
    exit 1
  fi
}

# @brief argparse__validate_integer_max VAR MAX — Exits 1 if $VAR > MAX.
argparse__validate_integer_max() {
  if (( ${!1} > ${2} )); then
    logging__error "Invalid value for '${1}': '${!1}' must be <= ${2}."
    exit 1
  fi
}

# @brief argparse__validate_path VAR OP — Exits 1 if the path in $VAR fails test OP.
#
# OP is a bash unary test operator (e.g. -d, -f, -e).
# Validation fails when the test does NOT hold.  An empty value is skipped.
argparse__validate_path() {
  local _val="${!1}"
  [[ -z "$_val" ]] && return 0
  local _ok=false
  case "$2" in
    -d) [[ -d "$_val" ]] && _ok=true ;;
    -f) [[ -f "$_val" ]] && _ok=true ;;
    -e) [[ -e "$_val" ]] && _ok=true ;;
    -x) [[ -x "$_val" ]] && _ok=true ;;
    -r) [[ -r "$_val" ]] && _ok=true ;;
    -s) [[ -s "$_val" ]] && _ok=true ;;
    -w) [[ -w "$_val" ]] && _ok=true ;;
    "! -"[dferswx])
      ! test "${2#! }" "$_val" && _ok=true ;;
    *)
      logging__error "argparse__validate_path: unsupported path test '${2}'."
      exit 1 ;;
  esac
  if [[ "$_ok" != true ]]; then
    logging__error "Invalid value for '${1}': '${_val}' failed path test '${2}'."
    exit 1
  fi
}

# @brief argparse__default VAR DEFAULT — Sets $VAR to DEFAULT if not already set.
argparse__default() {
  [ "${!1+defined}" ] && return 0
  local -n _d_ref="$1"
  _d_ref="$2"
  logging__info "Argument '${1}' set to default value \"${2}\"."
}

# @brief argparse__default_array VAR — Sets array $VAR to () if not already declared.
argparse__default_array() {
  declare -p "$1" &> /dev/null && return 0
  local -n _da_ref="$1"
  _da_ref=()
  logging__info "Argument '${1}' set to default value '(empty)'."
}

# @brief argparse__default_array_value VAR VALUE — Sets array $VAR from multi-line VALUE if not already declared.
#
# VALUE is the (already shell-expanded) multi-line string; use $'...' at the call site
# to let bash interpret escape sequences before passing to this function.
argparse__default_array_value() {
  declare -p "$1" &> /dev/null && return 0
  local -n _dav_ref="$1"
  mapfile -t _dav_ref < <(printf '%s' "$2" | grep -v '^$')
  local _disp="${2//$'\n'/, }"
  logging__info "Argument '${1}' set to default value \"${_disp}\"."
}
