"""sync-src.py — Assembles each feature's src/ directory from features/ + lib/ + features/bootstrap.sh:

  - features/*/metadata.yaml → src/*/devcontainer-feature.json
  - features/*/metadata.yaml → src/*/dependencies/*.yaml
  - features/*/install.bash  → src/*/install.bash (autogenerated header prepended)
  - lib/                     → src/*/_lib/
  - features/bootstrap.sh    → src/*/install.sh
  - features/*/files/        → src/*/files/ (copied, not symlinked)

Usage:
  python3 scripts/sync-src.py           # sync all features
  python3 scripts/sync-src.py --check   # verify src/ is up to date (exits non-zero if stale)
"""

from __future__ import annotations

import copy
import fnmatch
import json
import re
import sys
from pathlib import Path
import subprocess
import tempfile

import jsonschema
import yaml


SCRIPT_DIRPATH = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIRPATH))
from git_utils import git_owner_repo, git_repo_root


REPO_DIRPATH = git_repo_root()
REPO_OWNER, REPO_NAME = git_owner_repo()

# Constants
FEATURES_DIRPATH = REPO_DIRPATH / "features"
SRC_DIRPATH = REPO_DIRPATH / "src"
DERIVED_OPTIONS_FILEPATH = FEATURES_DIRPATH / "derived-options.yaml"
METADATA_SCHEMA_FILEPATH = FEATURES_DIRPATH / "metadata.schema.json"
OSPKG_MANIFEST_SCHEMA_FILEPATH = FEATURES_DIRPATH / "install-os-pkg" / "manifest.schema.json"
INSTALL_SCRIPT_TEMPLATES_DIRPATH = FEATURES_DIRPATH / "_templates"
LICENSE_URL = f"https://github.com/{REPO_OWNER}/{REPO_NAME}/blob/main/LICENSE"
DOC_URL_TEMPLATE = f"https://{REPO_OWNER}.github.io/{REPO_NAME}/features/{{feature_id}}"
_REMOTE_MANIFEST_URL = (
    "https://raw.githubusercontent.com/QuanTizEd8/SysSet/main"
    "/features/install-os-pkg/manifest.schema.json"
)
INSTALL_SCRIPT_HEADER_END_MARKER = "# END OF AUTOGENERATED BLOCK"
LIB_DIRPATH = REPO_DIRPATH / "lib"
BOOTSTRAP_FILEPATH = FEATURES_DIRPATH / "bootstrap.sh"


def run(check_only: bool = False):

    n_features: int = 0
    n_failures: dict[str, int] = {
        "read": 0,
        "augmentation": 0,
        "schema validation": 0,
        "sync": 0,
    }

    lib_files = gather_lib_files()
    bootstrap_file = gather_bootstrap()

    for feature_dirpath in sorted(FEATURES_DIRPATH.iterdir()):

        if not feature_dirpath.is_dir() or feature_dirpath.name[0] in (".", "_"):
            continue

        n_features += 1
        feature_id = feature_dirpath.name
        output_files: dict[Path, str] = {}

        metadata = read_metadata(feature_id)
        if metadata is None:
            n_failures["read"] += 1
            continue

        augmentation_ok = augment_metadata(feature_id, metadata)
        if not augmentation_ok:
            n_failures["augmentation"] += 1
            continue

        validation_ok = validate_metadata_schema(feature_id, metadata)
        if not validation_ok:
            n_failures["schema validation"] += 1
            continue

        dependency_manifests = generate_dependency_manifests(metadata)
        output_files.update(dependency_manifests)

        sanitize_markdown(metadata)

        metadata_json = generate_metadata_json(feature_id, metadata)
        output_files.update(metadata_json)

        install_script = generate_install_script(feature_id, metadata)
        output_files.update(install_script)
        output_files.update(lib_files)
        output_files.update(bootstrap_file)
        output_files.update(gather_feature_files(feature_id))

        sync_ok = sync_source_files(feature_id, output_files, check_only=check_only)
        if not sync_ok:
            n_failures["sync"] += 1

    log("Final results:")
    if any(n_failures.values()):
        n_failures_total = sum(n_failures.values())
        log(f"\n{n_failures_total}/{n_features} feature(s) failed validation.")
        return 1

    log(f"\n✅  All {n_features} features passed.")
    return 0


# Metadata Reading
# ----------------

def read_metadata(feature_id: str) -> dict | None:
    """Read and parse the metadata.yaml for the given feature ID."""
    metadata_filepath = FEATURES_DIRPATH / feature_id / "metadata.yaml"
    if not metadata_filepath.is_file():
        log(f"⛔ {feature_id}: metadata.yaml not found")
        return None

    try:
        data = yaml.safe_load(metadata_filepath.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        log(f"❌ {feature_id}: YAML parse error: {exc}")
        return None

    if not isinstance(data, dict):
        log(f"❌ {feature_id}: metadata.yaml does not contain a mapping (got {type(data).__name__})")
        return None

    return data


# Metadata Augmentation
# ---------------------

def augment_metadata(feature_id: str, metadata: dict) -> bool:
    """Generate the full options dict for a feature.

    Add derived options from features/derived-options.yaml,
    conditionally applying options with _apply_when
    based on the feature's full metadata dict.
    """

    options: dict = metadata.get("options", {})
    for option_id, option_def in _derived_options.items():
        if option_id in options:
            log(f"⛔ {feature_id}: option '{option_id}' is a derived option and cannot be manually defined in metadata.yaml")
            return False
        should_apply = (
            _evaluate_condition(option_def["_apply_when"], metadata)
            if "_apply_when" in option_def else True
        )
        if should_apply:
            options[option_id] = {k: v for k, v in option_def.items() if not k.startswith("_")}
    metadata["options"] = options
    return True


def _evaluate_condition(apply_when: dict, data: dict) -> bool:
    """Evaluate an _apply_when condition against the feature's full metadata dict."""
    jsonpath = apply_when["jsonpath"]
    exists, value = _resolve_jsonpath(jsonpath, data)
    condition = apply_when["condition"]
    if condition == "exists":
        return exists
    if condition == "not_exists":
        return not exists
    if condition == "equals":
        expected = apply_when["value"]
        return exists and value == expected
    if condition == "not_equals":
        expected = apply_when["value"]
        return not exists or value != expected
    raise ValueError(f"Unsupported condition: {condition}")


def _resolve_jsonpath(jsonpath: str, data: dict) -> tuple[bool, object]:
    """Resolve a simple JSONPath expression against the feature metadata dict.

    Supported JSONPath syntax:
    - Root object: $
    - Dot notation for object properties: $.property

    Returns
    -------
    exists
        Whether the path exists in the metadata dict.
    value
        The value at the path if it exists, or None if it does not exist.
    """
    if not jsonpath.startswith("$."):
        raise ValueError(f"Unsupported JSONPath expression: {jsonpath}")
    path_parts = jsonpath[2:].split(".")
    current = data
    for part in path_parts:
        if not isinstance(current, dict) or part not in current:
            return False, None
        current = current[part]
    return True, current


with DERIVED_OPTIONS_FILEPATH.open(encoding="utf-8") as _fh:
    _derived_options: dict = yaml.safe_load(_fh)


# Schema Validation
# -----------------

def validate_metadata_schema(feature_id: str, metadata: dict) -> bool:
    errs = sorted(
        _metadata_schema_validator.iter_errors(metadata),
        key=lambda e: list(e.absolute_path),
    )
    if errs:
        for err in errs:
            path = (
                " → ".join(str(p) for p in err.absolute_path)
                if err.absolute_path
                else "(root)"
            )
            log(f"❌ {feature_id}: {path}: {err.message}")
        return False

    return True


def _get_metadata_schema_validator():
    metadata_schema = json.loads(METADATA_SCHEMA_FILEPATH.read_text(encoding="utf-8"))
    _rewrite_remote_refs(metadata_schema)
    return jsonschema.Draft7Validator(metadata_schema)


def _rewrite_remote_refs(obj: object) -> None:
    """Replace the remote manifest $ref with the local file:// URI (in-place)."""
    if isinstance(obj, dict):
        if obj.get("$ref") == _REMOTE_MANIFEST_URL:
            obj["$ref"] = OSPKG_MANIFEST_SCHEMA_FILEPATH.as_uri()
        for v in obj.values():
            _rewrite_remote_refs(v)
    elif isinstance(obj, list):
        for item in obj:
            _rewrite_remote_refs(item)
    return


_metadata_schema_validator = _get_metadata_schema_validator()


# Dependency Manifest Generation
# ------------------------------

def generate_dependency_manifests(metadata: dict) -> dict[Path, str]:
    """Sync the dependencies/ directory for the given feature based on its metadata."""
    deps = metadata.get("_dependencies")
    if not deps:
        return {}

    dirpath = Path("dependencies")
    manifests = {}

    for lifecycle, groups in deps.items():
        for dep_name, dep_content in groups.items():
            dep_path = dirpath / lifecycle / f"{dep_name}.yaml"
            manifest = yaml.dump(dep_content, default_flow_style=False, sort_keys=False, allow_unicode=True)
            manifests[dep_path] = manifest
    return manifests


# Markdown Sanitation
# -------------------

def sanitize_markdown(metadata: dict) -> None:
    """Recursively process a value, stripping markdown from description fields."""

    metadata["description"] = _normalize_description(metadata["description"])

    if "options" in metadata:
        for option in metadata["options"].values():
            option["description"] = _normalize_description(option["description"])

    return


def _normalize_description(text: str) -> str:
    """Strip markdown and normalize whitespace for JSON output.

    Strips leading/trailing whitespace and collapses multiple consecutive
    blank lines to a single blank line, while preserving intentional
    paragraph structure.
    """
    text = _strip_markdown(text)
    lines = [line.rstrip() for line in text.splitlines()]
    # Collapse runs of blank lines
    result: list[str] = []
    prev_blank = False
    for line in lines:
        blank = not line.strip()
        if blank:
            if not prev_blank:
                result.append("")
            prev_blank = True
        else:
            result.append(line)
            prev_blank = False
    # Strip leading/trailing blank lines
    while result and not result[0]:
        result.pop(0)
    while result and not result[-1]:
        result.pop()
    return "\n".join(result)


def _strip_markdown(text: str) -> str:
    """Strip markdown formatting from a description string.

    Handles:
    - Images:   ![alt](url)        → alt
    - Links:    [text](url)        → text
    - Bold:     **text** / __text__ → text
    - Italic:   *text*              → text   (``_text_`` is intentionally left
                                              alone — too ambiguous with
                                              shell variables and identifiers)
    - HTML tags: <tag ...> / </tag> → (removed)
      Only real HTML is stripped: closing tags (</...>) and opening tags that
      carry attributes (contain whitespace).  Single-word angle-bracket tokens
      like <version>, <shell>, <home_dir> used as documentation placeholders
      are intentionally left untouched.

    Backtick code spans are intentionally preserved: they remain readable
    in plain text and are common in technical option descriptions.
    """
    if not text:
        return text
    # Images before links (avoid double-processing)
    text = re.sub(r"!\[([^\]]*)\]\([^)]*\)", r"\1", text)
    # Links
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    # Bold
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"__([^_]+)__", r"\1", text)
    # Italic (asterisk only)
    text = re.sub(r"\*([^*\n]+)\*", r"\1", text)
    # HTML tags: closing tags </foo> and opening tags with attributes <foo ...>
    # Single-word tokens like <version> or <shell> are NOT matched.
    text = re.sub(r"</[a-zA-Z][^>]*>", "", text)
    text = re.sub(r"<[a-zA-Z][^>]*\s[^>]*>", "", text)
    return text


# Metadata JSON Generation
# ------------------------

def generate_metadata_json(feature_id: str, metadata: dict) -> dict[Path, str]:
    """Generate devcontainer-feature.json content from parsed YAML data.

    Returns the JSON string (with trailing newline).
    """
    metadata_json_dict: dict = {
        "documentationURL": DOC_URL_TEMPLATE.format(feature_id=feature_id),
        "licenseURL": LICENSE_URL
    }

    for key, value in metadata.items():
        if key.startswith("_"):
            continue
        if key != "options":
            metadata_json_dict[key] = value
            continue

        options = {}
        for option_id, option_raw in value.items():
            option = {}
            for k, v in option_raw.items():
                if k == "type" and v == "array":
                    option[k] = "string"
                elif k in ("enum", "proposals"):
                    option[k] = [item["value"] for item in v]
                else:
                    option[k] = v
            options[option_id] = option
        metadata_json_dict[key] = options

    metadata_json = json.dumps(metadata_json_dict, sort_keys=True, indent=3, ensure_ascii=False) + "\n"
    return {Path("devcontainer-feature.json"): metadata_json}


# Install Script Generation
# -------------------------

def generate_install_script(feature_id: str, metadata: dict) -> dict[Path, str]:
    """Generate the full install.bash content for a feature.

    The generated content covers everything from the shebang (#!/usr/bin/env bash)
    through the argument-parsing block and default-variable initialisation, and is
    terminated by a single end marker:

        # END OF AUTOGENERATED BLOCK

    Everything after that marker in the file is hand-written implementation code
    and is never touched by this script.

    Options with ``type: array`` in metadata.yaml are treated as bash arrays:
    * CLI branch:      --flag <value>  (repeatable; each invocation appends)
    * env-var branch:  newline-delimited string split into an array
    * Defaults:        empty array  ()

    The ``type: array`` is serialised as ``type: string`` in devcontainer-feature.json
    (handled by metadata.py).
    """

    target_file = Path("install.bash")
    body_path = FEATURES_DIRPATH / feature_id / target_file

    if not body_path.exists():
        return {}

    body = body_path.read_text(encoding="utf-8").strip("\n")

    feature_name: str = metadata["name"]
    options: dict = metadata["options"]
    dependencies: dict | None = metadata.get("_dependencies")

    header = _generate_block(feature_name, options, dependencies)
    full_script = _shfmt_format(f"{header}\n\n{body}\n")
    return {target_file: full_script}


def _generate_block(feature_name: str, options: dict, dependencies: dict | None = None) -> str:
    """Return the full generated content from shebang to END marker (inclusive).

    The returned string ends with ``# END OF AUTOGENERATED BLOCK\\n``.
    If ``_dependencies.run`` contains a ``base`` key, a ``_base_deps__install``
    call is emitted as the last statement before the end marker.
    If ``_dependencies.build`` is non-empty, dep-group helper functions are emitted.
    """
    run_deps: dict = (dependencies or {}).get("run") or {}
    build_deps: dict = (dependencies or {}).get("build") or {}
    parts = [
        _render_template("preamble", FEATURE_NAME=feature_name),
        _section_usage(options),
        _section_arg_parse(options),
        _section_debug_flag(),
        _section_defaults(options),
        _section_validation(options),
        _section_unexport(options),
        _section_dep_helpers(run_deps, build_deps),
        _section_base_deps_call(run_deps),
        INSTALL_SCRIPT_HEADER_END_MARKER,
    ]
    return "\n\n".join(p for p in parts if p)


def _section_usage(options: dict) -> str:
    """Emit the __usage__() shell function."""
    entries: list[tuple[str, str, str, bool]] = []
    for key, opt in options.items():
        typ = opt["type"]
        flag_str = f"  {_opt_to_flag(key)} {_usage_type_hint(opt)}"
        has_default = "default" in opt
        default = opt.get("default", "")
        is_required = not has_default
        if typ == "boolean":
            disp_default = "true" if default else "false"
        elif typ == "array":
            disp_default = ""
        else:
            disp_default = str(default) if has_default and default is not None else ""
        desc = _first_sentence(opt.get("description", ""))
        entries.append((flag_str, desc, disp_default, is_required))

    help_flag = "  -h, --help"
    col_width = max((len(f) for f, *_ in entries), default=len(help_flag))
    col_width = max(col_width, len(help_flag))

    lines = ["__usage__() {", "  cat << 'EOF'", "Usage: install.bash [OPTIONS]", "", "Options:"]
    for (flag_str, desc, disp_default, is_required), _ in zip(entries, options.items()):
        padding = " " * (col_width - len(flag_str) + 2)
        if is_required:
            desc_field = f"{desc} (required)"
        elif disp_default:
            desc_field = f'{desc} (default: "{disp_default}")'
        else:
            desc_field = desc
        lines.append(f"{flag_str}{padding}{desc_field}")
    help_padding = " " * (col_width - len(help_flag) + 2)
    lines.append(f"{help_flag}{help_padding}Show this help")
    lines.extend(["EOF", "  return", "}"])
    return "\n".join(lines)


def _section_arg_parse(options: dict) -> str:
    """Emit the if/else/fi CLI-vs-env-var argument parsing block."""
    cli_inits: list[str] = []
    case_arms: list[str] = []
    env_reads: list[str] = []

    for key, opt in options.items():
        vname = _opt_to_var(key)
        typ = opt.get("type", "string")
        flag = _opt_to_flag(key)
        # Arrays are intentionally NOT pre-initialised: bash +=() on an unset variable
        # is safe, and pre-setting to () would fool the declare-based default check.
        if typ != "array":
            if "default" not in opt:
                cli_inits.append(f'  {vname}=""')
            else:
                cli_inits.append(f"  {vname}={_shell_val(opt['default'], typ)}")
        if typ == "array":
            case_arms.append(_render_template("case_arm_array", FLAG=flag, VAR=vname, KEY=key))
            env_reads.append(_render_template("env_read_array", VAR=vname, KEY=key))
        else:
            case_arms.append(_render_template("case_arm_scalar", FLAG=flag, VAR=vname, KEY=key))
            env_reads.append(_render_template("env_read_scalar", VAR=vname, KEY=key))

    lines = [
        'if [ "$#" -gt 0 ]; then',
        '  echo "ℹ️ Script called with arguments: $*" >&2',
    ]
    lines.extend(cli_inits)
    lines.extend(['  while [ "$#" -gt 0 ]; do', "    case $1 in"])
    lines.extend(case_arms)
    lines.extend([
        "      -h | --help)",
        "        __usage__",
        "        exit 0",
        "        ;;",
        "      --*)",
        "        echo \"⛔ Unknown option: '${1}'\" >&2",
        "        exit 1",
        "        ;;",
        "      *)",
        "        echo \"⛔ Unexpected argument: '${1}'\" >&2",
        "        exit 1",
        "        ;;",
        "    esac",
        "  done",
        "else",
        '  echo "ℹ️ Script called with no arguments. Read environment variables." >&2',
    ])
    lines.extend(env_reads)
    lines.append("fi")
    return "\n".join(lines)


def _section_debug_flag() -> str:
    return '[[ "${DEBUG:-}" == true ]] && set -x'


def _section_defaults(options: dict) -> str:
    """Emit the '# Apply defaults.' block."""
    blocks = ["# Apply defaults."]
    for key, opt in options.items():
        vname = _opt_to_var(key)
        typ = opt.get("type", "string")
        if "default" not in opt:
            continue
        if typ == "array":
            raw_default = opt["default"]
            if raw_default == "" or raw_default is None:
                blocks.append(_render_template("default_array_empty", VAR=vname, KEY=key))
            else:
                # Embed the default as an ANSI-C quoted string so newlines are preserved.
                escaped = (
                    str(raw_default)
                    .replace("\\", "\\\\")
                    .replace("'", "\\'")
                    .replace("\n", "\\n")
                    .replace("\r", "\\r")
                )
                disp = ", ".join(str(raw_default).splitlines())
                blocks.append(_render_template("default_array_value", VAR=vname, ESCAPED=escaped, KEY=key, DISP=disp))
        else:
            rhs = _shell_val(opt["default"], typ)
            if typ == "boolean":
                disp = "true" if opt["default"] else "false"
            elif opt["default"] == "" or opt["default"] is None:
                disp = ""
            else:
                disp = str(opt["default"])
            blocks.append(_render_template("default_scalar", VAR=vname, RHS=rhs, KEY=key, DISP=disp))
    return "\n".join(blocks)


def _section_validation(options: dict) -> str:
    """Emit required-argument checks and enum validation. Returns '' if neither applies."""
    required_opts = [(k, v) for k, v in options.items() if "default" not in v]
    enum_opts = [(k, v) for k, v in options.items() if v.get("enum")]
    if not required_opts and not enum_opts:
        return ""

    parts: list[str] = []
    if required_opts:
        checks: list[str] = []
        for key, opt in required_opts:
            vname = _opt_to_var(key)
            tpl = "validation_required_array" if opt.get("type", "string") == "array" else "validation_required_scalar"
            checks.append(_render_template(tpl, VAR=vname, KEY=key))
        parts.append("# Check required arguments.\n" + "\n".join(checks))

    if enum_opts:
        validations: list[str] = []
        for key, opt in enum_opts:
            vname = _opt_to_var(key)
            typ = opt.get("type", "string")
            values = [item["value"] if isinstance(item, dict) else str(item) for item in opt["enum"]]
            expected = ", ".join(repr(v) if v == "" else v for v in values)
            pattern = " | ".join("''" if v == "" else v for v in values)
            tpl = "validation_enum_array" if typ == "array" else "validation_enum_scalar"
            validations.append(_render_template(tpl, VAR=vname, KEY=key, PATTERN=pattern, EXPECTED=expected))
        parts.append("# Validate enum options.\n" + "\n".join(validations))

    return "\n\n".join(parts)


def _section_unexport(options: dict) -> str:
    """Emit the 'declare +x' unexport line for all scalar option variables."""
    scalar_vars = [
        _opt_to_var(k) for k, v in options.items() if v.get("type", "string") != "array"
    ]
    if not scalar_vars:
        return ""
    return "\n".join([
        "# Unexport option variables — values remain accessible in this script but",
        "# are not inherited by child processes.",
        "declare +x " + " ".join(scalar_vars),
    ])


def _section_dep_helpers(run_deps: dict, build_deps: dict) -> str:
    """Emit _<group>_deps__install() / _<group>_deps__cleanup() helper functions."""
    if not run_deps and not build_deps:
        return ""
    blocks = ["# ── dep-group helpers (generated) ──────────────────────────────────────────────"]
    for group_name in run_deps:
        blocks.append(_render_template("dep_helper_run", SAFE=group_name.replace("-", "_"), GROUP=group_name))
    for group_name in build_deps:
        blocks.append(_render_template("dep_helper_build", SAFE=group_name.replace("-", "_"), GROUP=group_name))
    return "\n".join(blocks)


def _section_base_deps_call(run_deps: dict) -> str:
    """Emit the root-guarded _base_deps__install() call, or '' if no base group."""
    if "base" not in run_deps:
        return ""
    return _render_template("base_deps_call")


def _shfmt_format(text: str) -> str:
    """Format a bash script fragment through shfmt, respecting .editorconfig.

    Writes to a temp file in the repo root so shfmt finds the .editorconfig
    style settings.  Returns *text* unchanged if shfmt is not on PATH.
    """
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".sh",
        dir=REPO_DIRPATH,
        delete=False,
        encoding="utf-8",
    ) as tmp:
        tmp.write(text)
        tmp_path = Path(tmp.name)
    try:
        result = subprocess.run(
            ["shfmt", "-w", str(tmp_path)],
            capture_output=True,
            cwd=REPO_DIRPATH,
        )
        if result.returncode == 0:
            return tmp_path.read_text(encoding="utf-8")
        return text
    except FileNotFoundError:
        return text
    finally:
        tmp_path.unlink(missing_ok=True)


def _first_sentence(text: str) -> str:
    """Return the first non-empty line of a description."""
    for line in text.splitlines():
        line = line.strip()
        if line:
            return line
    return text.strip()


def _opt_to_var(key: str) -> str:
    """Convert a schema-validated option key to its installer env-var name.

    Option keys are constrained by features/metadata.schema.json to start with an
    ASCII letter and then contain only ASCII letters, digits, underscores, or
    hyphens. Given that contract, env-var generation is just uppercase plus
    '-' -> '_'.
    """
    return key.upper().replace("-", "_")


def _opt_to_flag(key: str) -> str:
    """Convert an option key to its --flag form."""
    return f"--{key}"


def _shell_val(default, typ: str) -> str:
    """Format a YAML default value as a shell assignment RHS (non-array types only)."""
    if typ == "boolean":
        return "true" if default else "false"
    if default == "" or default is None:
        return '""'
    return f'"{default}"'


def _usage_type_hint(opt: dict) -> str:
    """Return a concise type hint for the --help usage line."""
    typ = opt["type"]
    enum_raw = opt.get("enum", [])
    enum_values = [item["value"] if isinstance(item, dict) else str(item) for item in enum_raw]
    if typ == "boolean":
        return "{true,false}"
    if typ == "array":
        if enum_values:
            return "{" + "|".join(enum_values) + "}  (repeatable)"
        return "<value>  (repeatable)"
    if enum_values:
        return "{" + "|".join(enum_values) + "}"
    return "<value>"


def _render_template(name: str, **subs: str) -> str:
    """Load a shell snippet template from features/_templates/ and substitute @@KEY@@ placeholders."""
    template = _install_script_templates[name]
    for key, val in subs.items():
        template = template.replace(f"@@{key}@@", val)
    return template


def _read_templates() -> dict[str, str]:
    """Read all templates from the _templates directory and return a mapping of template name to content."""
    templates = {}
    for template_path in INSTALL_SCRIPT_TEMPLATES_DIRPATH.glob("*.tmpl"):
        template_name = template_path.name.removesuffix(".sh.tmpl")
        templates[template_name] = template_path.read_text(encoding="utf-8").rstrip("\n")
    return templates


_install_script_templates = _read_templates()


# File Gathering (lib, bootstrap, feature files/)
# ------------------------------------------------

def gather_lib_files() -> dict[Path, str]:
    """Read all files from lib/ and return them keyed by their _lib/-relative output paths."""
    files: dict[Path, str] = {}
    for src_path in sorted(LIB_DIRPATH.rglob("*")):
        if not src_path.is_file():
            continue
        rel = src_path.relative_to(LIB_DIRPATH)
        files[Path("_lib") / rel] = src_path.read_text(encoding="utf-8")
    return files


def _gitignore_basename_patterns() -> list[str]:
    """Return the basename-only patterns from the repo .gitignore.

    Basename-only patterns are those without a '/' in their body — they match
    any file regardless of directory depth, exactly as git does.  Path-anchored
    patterns (e.g. ``/src/``, ``docs/features/``) are intentionally excluded so
    that this function returns only file-name patterns (e.g. ``.DS_Store``,
    ``._*``, ``Thumbs.db``).
    """
    gitignore = REPO_DIRPATH / ".gitignore"
    if not gitignore.is_file():
        return []
    patterns: list[str] = []
    for raw in gitignore.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("!"):
            continue
        # Directory-only patterns (trailing '/') are not file patterns.
        if line.endswith("/"):
            continue
        # Strip leading '/' anchors before the slash check.
        body = line.lstrip("/")
        # Skip patterns that contain a '/' — they are path-specific, not
        # basename patterns.
        if "/" in body:
            continue
        patterns.append(body)
    return patterns


_GITIGNORE_BASENAME_PATTERNS: list[str] = _gitignore_basename_patterns()


def _is_junk_file(name: str) -> bool:
    """Return True if the filename matches any basename-only .gitignore pattern.

    Developers control which files are considered junk by editing .gitignore;
    no patterns are hardcoded here.
    """
    return any(fnmatch.fnmatch(name, p) for p in _GITIGNORE_BASENAME_PATTERNS)


def gather_bootstrap() -> dict[Path, str]:
    """Read features/bootstrap.sh and return it keyed as install.sh."""
    return {Path("install.sh"): BOOTSTRAP_FILEPATH.read_text(encoding="utf-8")}


def gather_feature_files(feature_id: str) -> dict[Path, str]:
    """Read features/<id>/files/** and return them keyed by their files/-relative output paths.

    Only git-tracked files are included.  This ensures that OS-generated
    artefacts (e.g. ``.DS_Store``) that happen to exist on disk but were never
    committed are silently ignored without any hardcoded filename list.
    """
    files_dir = FEATURES_DIRPATH / feature_id / "files"
    if not files_dir.is_dir():
        return {}
    ls = subprocess.run(
        ["git", "ls-files", "-z", "--", "."],
        capture_output=True, text=True, check=True,
        cwd=files_dir,
    )
    tracked = frozenset(
        files_dir / rel for rel in ls.stdout.split("\0") if rel
    )
    return {
        Path("files") / src_path.relative_to(files_dir): src_path.read_text(encoding="utf-8")
        for src_path in sorted(files_dir.rglob("*"))
        if src_path.is_file() and src_path in tracked
    }


# File Sync
# ---------

def sync_source_files(feature_id: str, new_files: dict[Path, str], check_only: bool = False) -> bool:

    feature_src_dir = SRC_DIRPATH / feature_id
    old_files = {
        path.relative_to(feature_src_dir): path.read_text(encoding="utf-8")
        for path in sorted(feature_src_dir.rglob("*"))
        if path.is_file() and not _is_junk_file(path.name)
    } if feature_src_dir.exists() else {}

    is_in_sync = True

    for new_filepath, new_content in new_files.items():

        if new_filepath not in old_files:
            if check_only:
                is_in_sync = False
                log(f"⛔ {feature_id}: {new_filepath} is missing")
            else:
                (feature_src_dir / new_filepath).parent.mkdir(parents=True, exist_ok=True)
                (feature_src_dir / new_filepath).write_text(new_content, encoding="utf-8")
                log(f"✅ {feature_id}: {new_filepath} created")
            continue

        if old_files[new_filepath] == new_content:
            log(f"✅ {feature_id}: {new_filepath} unchanged")
            continue

        if check_only:
            is_in_sync = False
            log(f"⛔ {feature_id}: {new_filepath} is stale")
        else:
            (feature_src_dir / new_filepath).write_text(new_content, encoding="utf-8")
            log(f"✅ {feature_id}: {new_filepath} updated")

    # Check/remove stale files that are no longer declared in metadata.
    for old_filepath in old_files:
        if old_filepath not in new_files:
            if check_only:
                is_in_sync = False
                log(f"⛔ {feature_id}: {old_filepath} must be removed")
            else:
                (feature_src_dir / old_filepath).unlink()
                log(f"🗑️  {feature_id}: {old_filepath} removed")
    return is_in_sync


# Logging
# -------

def log(msg: str) -> None:
    print(msg, file=sys.stderr)


if __name__ == "__main__":
    check_only = "--check" in sys.argv
    sys.exit(run(check_only=check_only))
